import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    shipments: 'My Shipments',
    documents: 'Documents',
    messages: 'Messages',
    payments: 'Payments',
    profile: 'Profile',
    settings: 'Settings',
    signOut: 'Sign out',
    welcome: 'Welcome back',
    notifications: 'Notifications',
    support: 'Need assistance?',
    contactSupport: 'Contact Support',
    inTransit: 'In Transit',
    inWarehouse: 'In Warehouse',
    totalShipments: 'Total Shipments',
    issues: 'Issues',
    activeShipments: 'Active Shipments',
    viewAll: 'View all',
    recentActivity: 'Recent Activity',
    noActiveShipments: 'You don\'t have any active shipments at the moment.',
    updatedOn: 'Updated on',
    from: 'From',
    to: 'To',
    weight: 'Weight',
    volume: 'Volume',
    status: 'Status',
    origin: 'Origin',
    destination: 'Destination',
    description: 'Description',
    estimatedDelivery: 'Estimated Delivery',
    pending: 'Pending',
    draft: 'Draft',
    processing: 'Processing',
    customs: 'Customs Clearance',
    delivered: 'Delivered',
    issue: 'Issue',
    statsInTransit: 'In Transit',
    statsInWarehouse: 'In Warehouse',
    statsTotalShipments: 'Total Shipments',
    statsIssues: 'Issues',
    hereIsOverview: 'Here\'s an overview of your shipments',
    in_transit:'In Transit',
    warehouse: 'In Warehouse',
    all: 'All',
    created_at: 'Created on',
    shipment_timeLine: 'Shipment Timeline',
    in_customs_clearance: 'In Customs Clearance',
    shipment_created: 'Shipment Created',
    processing_started: 'Processing Started',
    arrived_at_warehouse: 'Arrived at Warehouse',
    delivered_successfully: 'Delivered Successfully',
    issue_reported: 'Issue Reported',
    my_shipments: 'My Shipments',
    search_shipments: 'Search shipments...',
    filter_by_status: 'Filter by Status',
    track_the_progress: 'Track the progress of your shipment',
    download: 'Download',
    no_documents_yet: 'No documents available yet.',
    quick_actions: 'Quick Actions',
    contact_the_agent_in_charge: 'Contact the agent in charge',
    notifications_description: 'Stay updated with your shipment status and important alerts',
    all_notifications: 'All Notifications',
    unread_count: (params: { count: number }) => `You have ${params.count} unread notifications`,
    mark_all_as_read: 'Mark all as read',
    no_notifications: 'No notifications',
    no_notifications_description: 'You\'re all caught up! No new notifications at the moment.',
    view_all_notifications: 'View all notifications',
    view_profile_analytics: 'View your profile and shipping analytics',
    member_since: 'Member since',
    completion_rate: 'Completion Rate',
    active_shipments: 'Active Shipments',
    completed: 'Completed',
    monthly_shipments: 'Monthly Shipments',
    shipment_status_distribution: 'Shipment Status Distribution',
    manage_account_preferences: 'Manage your account preferences',
    change_avatar: 'Change avatar',
    name: 'Name',
    email: 'Email',
    preferences: 'Preferences',
    language_preference: 'Language',
    email_notifications: 'Email notifications',
    receive_notifications: 'Receive notifications about your shipments',
    security: 'Security',
    change_password: 'Change password',
    cancel: 'Cancel',
    save_changes: 'Save changes',
    tracking_number: 'Tracking #',
    my_invoices: 'My Invoices',
    invoice_number: 'Invoice Number',
    amount: 'Amount',
    due_date: 'Due Date',
    payment_status: 'Payment Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    search_invoices: 'Search invoices...',
    filter_by_payment_status: 'Filter by Payment Status',
    total_paid: 'Total Paid',
    total_unpaid: 'Total Unpaid',
    total_overdue: 'Total Overdue',
    pay_now: 'Pay Now',
    view_invoice: 'View Invoice',
    download_invoice: 'Download Invoice',
    invoice_date: 'Invoice Date',
    payment_due: 'Payment Due',
    payment_received: 'Payment Received',
    invoice_details: 'Invoice Details',
    manage_messages: 'Manage your shipment communications',
    new_message: 'New Message',
    new: 'New',
    search_messages: 'Search messages...',
    no_conversations: 'No conversations match your search',
    online: 'Online',
    write_message: 'Write your message...',
    send: 'Send',
    today: 'Today',
    yesterday: 'Yesterday',
    view_profile: 'View Profile',
    mark_as_read: 'Mark as read',
    attach_file: 'Attach file',
    show_less: 'Show Less',
    show_all: 'Show All',
    loading: 'Loading...',
    manage_documents: 'Manage all your shipment documents',
    search_documents: 'Search documents...',
    all_documents: 'All Documents',
    invoices: 'Invoices',
    customs_declarations: 'Customs Declarations',
    bills_of_lading: 'Bills of Lading',
    certificates: 'Certificates',
    other_documents: 'Other Documents',
    document: 'Document',
    shipment: 'Shipment',
    type: 'Type',
    uploaded: 'Uploaded',
    actions: 'Actions',
    no_documents_found: 'No documents found',
    no_documents_match_filters: 'No documents match your current filters.',
    clear_filters: 'Clear filters',
    upload_document: 'Upload Document',
    showing_documents: (params: { count: number }) => `Showing ${params.count} ${params.count === 1 ? 'document' : 'documents'}`,
    filtered: '(filtered)',
    location: 'Location',
    invoice: 'Invoice',
    bill_of_lading: 'Bill of Lading',
    certificate: 'Certificate',
    other_document: 'Other Document',
    shipment_type: 'Shipment Type',
    air_shipment: 'Air Freight',
    sea_shipment: 'Sea Freight',
    type_air: 'Air',
    type_sea: 'Sea',
    shipments_found: 'Shipments found',
    shipment_found: 'Shipment found',
    overview: 'Overview',
    analytics: 'Analytics',
    delivery_performance: 'Delivery Performance',
    avg_delivery_time: 'Average Delivery Time',
    days: 'days',
    on_time_delivery: 'On-time Delivery',
    delayed_shipments: 'Delayed Shipments',
    cancelled: 'Cancelled',
    shipping_destinations: 'Shipping Destinations',
    other: 'Other',
    recent_activity: 'Recent Activity',
    no_recent_activity: 'No recent activity',
    last_12_months: 'Last 12 months',
    try_adjusting_filters: 'Try adjusting your filters or search criteria',
    no_shipments_found: 'No shipments found',
    update_personal_information: 'Update your personal information',
    notification_settings: 'Notification settings',
    manage_how_we_contact_you: 'Manage how we contact you',
    password: 'Password',
    last_changed: 'Last changed',
    months_ago: 'months ago',
    connected_devices: 'Connected devices',
    last_updated: 'Last updated',
    manage_security_settings: 'Manage your security settings',
    customize_your_experience: 'Customize your experience',
    back: 'Back',
    download_all: 'Download all',
    shipment_details: 'Shipment Details',
    additional_information: 'Additional Information',
    incoterms: 'Incoterms',
    containers: 'Containers',
    insurance: 'Insurance',
    customs_status: 'Customs Status',
    parties: 'Parties',
    shipper: 'Shipper',
    consignee: 'Consignee',
    claim: 'Claim',
    contact_information: 'Contact Information',
    account_manager: 'Account Manager',
    agent_in_charge: 'Agent in charge',
    user_identifier: 'identifier',
    contact_agent: 'Contact agent',
    shipment_reference: 'Shipment reference',
    message: 'Message',
    write_your_message_here: 'Write your message here...',
    send_message: 'Send message',
    sending: 'Sending...',
    message_sent_successfully: 'Message sent successfully',
    available: 'Available',
    department: 'Department',
    position: 'Position',
    languages: 'Languages',
    availability: 'Availability',
    file_claim: 'File a Claim',
    claim_type: 'Claim Type',
    select_claim_type: 'Select claim type',
    write_your_claim_here: 'Write your claim details here...',
    submit_claim: 'Submit Claim',
    claim_sent_successfully: 'Claim sent successfully',
    claim_agent_notification: 'Your claim will be sent to the agent in charge and their supervisor. We will process your request as soon as possible.',
    request_agent_change: 'Request Agent Change',
    delivery_issue: 'Delivery Issue',
    damaged_goods: 'Damaged Goods',
    missing_items: 'Missing Items',
    customs_issue: 'Customs Issue',
    delay_complaint: 'Delay Complaint',
    billing_issue: 'Billing Issue',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    saving: 'Saving...',
    security_requirements: 'Security Requirements',
    password_req_length: 'At least 8 characters',
    password_req_uppercase: 'One uppercase letter',
    password_req_lowercase: 'One lowercase letter',
    password_req_number: 'One number',
    password_req_special: 'One special character',
    password_change_instruction: 'Use a strong password that you don\'t use on any other site.',
    error_current_password_required: 'Current password is required',
    error_password_requirements: 'Your password doesn\'t meet all requirements',
    error_passwords_dont_match: 'Passwords don\'t match',
    password_changed_successfully: 'Password changed successfully',
    login: 'Log in',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    demoAccounts: 'Demo accounts',
    allRightsReserved: '© 2025 ShipTrack. All rights reserved.',
    portal: 'Logistics tracking portal',
    invalidCredentials: 'Invalid credentials. Please try again.',
    emailPlaceholder: 'you@example.com',
    language: 'Language',
    english: 'English',
    french: 'French',
    resetPassword: 'Reset Password',
    resetPasswordInstructions: 'Enter your email and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send reset link',
    resetEmailSent: 'Email sent',
    resetEmailSentDetails: 'Check your inbox for a link to reset your password. If you don\'t see it, check your spam folder.',
    resetEmailError: 'Failed to send reset email. Please try again.',
    backToLogin: 'Back to login',
    createNewPassword: 'Create New Password',
    createNewPasswordInstructions: 'Your password must be different from previous passwords.',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Enter new password',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Confirm your password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordRequirementsNotMet: 'Password does not meet all requirements',
    resetting: 'Resetting...',
    passwordResetSuccess: 'Password updated',
    passwordResetSuccessDetails: 'Your password has been reset successfully. You can now login with your new password.',
    proceedToLogin: 'Proceed to login',
    invalidResetToken: 'Invalid or expired reset token. Please request a new reset link.',
    minLength: 'At least 8 characters',
    upperCase: 'At least 1 uppercase letter',
    lowerCase: 'At least 1 lowercase letter',
    number: 'At least 1 number',
    specialChar: 'At least 1 special character',
    new_message_instruction: 'Select a shipment and write your message. Your inquiry will be sent to the assigned agent.',
    select_shipment: 'Select Shipment',
    select_a_shipment: '-- Select a shipment --',
    subject: 'Subject',
    enter_subject: 'Enter subject',
    assigned_agent: 'Assigned Agent',
    write_your_message: 'Write your message...',
    error_select_shipment: 'Please select a shipment',
    error_message_required: 'Message is required',
    inquiry_about: 'Inquiry about',
    away: 'Away',
    offline: 'Offline',
    files_attached: 'Files attached',
    attached_files: 'Attached files',
    filters: 'filters',
    manage_invoices: 'Manage all your invoices',
    all_read: "All read",
    no_unread_notifications: "No unread notifications",
    dismiss: "Dismiss",
    // Agent-specific translations
    transit_files: 'Transit Files',
    clients: 'Clients',
    client_management: 'Client Management',
    manage_client_portfolio: 'Manage your client portfolio and their information',
    new_client: 'New Client',
    create_client: 'Create Client',
    new_file: 'New File',
    export: 'Export',
    manage_transit_files: 'Manage all your transit files and shipments',
    files_found: 'files found',
    file_found: 'file found',
    no_files_found: 'No files found',
    no_files_match_filters: 'No files match your current search criteria.',
    clear_all_filters: 'Clear all filters',
    sort_by: 'Sort by',
    reference: 'Reference',
    client: 'Client',
    assigned_to: 'Assigned to',
    creation_date: 'Creation date',
    creation_date_from: 'Creation date (from)',
    creation_date_to: 'Creation date (to)',
    all_statuses: 'All statuses',
    all_types: 'All types',
    all_clients: 'All clients',
    all_agents: 'All agents',
    air: 'Air',
    sea: 'Sea',
    transport_type: 'Transport type',
    active_filters: 'Active filters',
    search: 'Search',
    filter_by: 'Filter by',
    clear: 'Clear',
    view_details: 'View details',
    edit: 'Edit',
    company: 'Company',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    active: 'Active',
    inactive: 'Inactive',
    no_clients_found: 'No clients found',
    no_clients_match_filters: 'No clients match your current search criteria.',
    agent_dashboard: 'Agent Dashboard',
    manage_files_clients: 'Manage your transit files and clients',
    files: 'Files',
    found: 'found',
    no_files_available: 'No transit files available at the moment.',
    staff: 'Staff',
    declarations: 'Declarations',
    agent: 'Agent',
    manageFilesAndClients: 'Manage your transit files and clients',
    createClient: 'Create Client',
    newFile: 'New File',
    searchPlaceholder: 'Search by reference, origin, destination...',
    clearAll: 'Clear All',
    allStatuses: 'All Statuses',
    transportType: 'Transport Type',
    allTypes: 'All Types',
    allClients: 'All Clients',
    assignedTo: 'Assigned To',
    allAgents: 'All Agents',
    cityCountryPlaceholder: 'City, country...',
    creationDateFrom: 'Creation Date (From)',
    creationDateTo: 'Creation Date (To)',
    activeFilters: 'Active filters:',
    filesFound: 'file(s) found',
    sortBy: 'Sort by:',
    creationDate: 'Creation Date',
    noFilesFound: 'No Files Found',
    noFilesFoundMessage: 'No files match your search criteria.',
    noFilesAvailable: 'No transit files available at the moment.',
    clearFilters: 'Clear Filters',
    operations: 'Operations',
    finance: 'Finance',
    itemsPerPage: 'Items per page',
    view: 'View',
    of: 'of',
    searchAgent: 'Search Agent',
    searchClient: 'Search Client',
  },
  fr: {
    dashboard: 'Tableau de bord',
    shipments: 'Mes expéditions',
    documents: 'Documents',
    messages: 'Messages',
    payments: 'Paiements',
    profile: 'Profil',
    settings: 'Paramètres',
    signOut: 'Déconnexion',
    welcome: 'Bienvenue',
    notifications: 'Notifications',
    support: 'Besoin d\'aide ?',
    contactSupport: 'Contacter le support',
    inTransit: 'En transit',
    inWarehouse: 'En entrepôt',
    totalShipments: 'Total des expéditions',
    issues: 'Problèmes',
    activeShipments: 'Expéditions actives',
    viewAll: 'Voir tout',
    recentActivity: 'Activité récente',
    noActiveShipments: 'Vous n\'avez aucune expédition active en ce moment.',
    updatedOn: 'Mis à jour le',
    from: 'De',
    to: 'Vers',
    weight: 'Poids',
    volume: 'Volume',
    status: 'Statut',
    origin: 'Origine',
    destination: 'Destination',
    description: 'Description',
    estimatedDelivery: 'Livraison estimée',
    pending: 'En attente',
    draft: 'Brouillon',
    processing: 'En traitement',
    customs: 'Dédouanement',
    delivered: 'Livré',
    issue: 'Problème',
    statsInTransit: 'En Transit',
    statsInWarehouse: 'En Entrepôt',
    statsTotalShipments: 'Total des Expéditions',
    statsIssues: 'Problèmes',
    hereIsOverview: 'Voici un aperçu de vos expéditions',
    in_transit:'En Transit',
    warehouse: 'En Entrepôt',
    all: 'Tout',
    created_at: 'Créé le',
    shipment_timeLine: 'Calendrier d\'expédition',
    in_customs_clearance: 'En dédouanement',
    shipment_created: 'Expédition créée',
    processing_started: 'Traitement démarré',
    arrived_at_warehouse: 'Arrivé à l\'entrepôt',
    delivered_successfully: 'Livré avec succès',
    issue_reported: 'Problème signalé',
    my_shipments: 'Mes Expéditions',
    search_shipments: 'Rechercher expédition...',
    filter_by_status: 'Filtre par statut',
    track_the_progress: 'Suivez la progression de votre envoi',
    download: 'Télécharger',
    no_documents_yet: 'Aucun document disponible pour le moment.',
    quick_actions: 'Actions rapides',
    contact_the_agent_in_charge: 'Contacter l\'agent en charge',
    notifications_description: 'Restez informé de l\'état de vos expéditions et des alertes importantes',
    all_notifications: 'Toutes les notifications',
    unread_count: (params: { count: number }) => `Vous avez ${params.count} notifications non lues`,
    mark_all_as_read: 'Tout marquer comme lu',
    no_notifications: 'Aucune notification',
    no_notifications_description: 'Vous êtes à jour ! Aucune nouvelle notification pour le moment.',
    view_all_notifications: 'Voir toutes les notifications',
    view_profile_analytics: 'Consultez votre profil et vos analyses d\'expédition',
    member_since: 'Membre depuis',
    completion_rate: 'Taux de réussite',
    active_shipments: 'Expéditions actives',
    completed: 'Terminées',
    monthly_shipments: 'Expéditions mensuelles',
    shipment_status_distribution: 'Distribution des statuts d\'expédition',
    manage_account_preferences: 'Gérez vos préférences de compte',
    change_avatar: 'Changer l\'avatar',
    name: 'Nom',
    email: 'Email',
    preferences: 'Préférences',
    language_preference: 'Langue',
    email_notifications: 'Notifications par email',
    receive_notifications: 'Recevoir des notifications concernant vos expéditions',
    security: 'Sécurité',
    change_password: 'Changer le mot de passe',
    cancel: 'Annuler',
    save_changes: 'Enregistrer les modifications',
    tracking_number: 'N° de suivi',
    my_invoices: 'Mes Factures',
    invoice_number: 'Numéro de facture',
    amount: 'Montant',
    due_date: 'Date d\'échéance',
    payment_status: 'Statut de paiement',
    paid: 'Payée',
    unpaid: 'Non payée',
    overdue: 'En retard',
    search_invoices: 'Rechercher des factures...',
    filter_by_payment_status: 'Filtrer par statut de paiement',
    total_paid: 'Total payé',
    total_unpaid: 'Total non payé',
    total_overdue: 'Total en retard',
    pay_now: 'Payer maintenant',
    view_invoice: 'Voir la facture',
    download_invoice: 'Télécharger la facture',
    invoice_date: 'Date de facturation',
    payment_due: 'Paiement dû',
    payment_received: 'Paiement reçu',
    invoice_details: 'Détails de la facture',
    manage_messages: 'Gérez vos communications d\'expédition',
    new_message: 'Nouveau message',
    new: 'Nouveau',
    search_messages: 'Rechercher messages...',
    no_conversations: 'Aucune conversation ne correspond à votre recherche',
    online: 'En ligne',
    write_message: 'Écrivez votre message...',
    send: 'Envoyer',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    view_profile: 'Voir le profil',
    mark_as_read: 'Marquer comme lu',
    attach_file: 'Joindre un fichier',
    show_less: 'Voir moins',
    show_all: 'Voir tout',
    loading: 'Chargement...',
    manage_documents: 'Gérez tous vos documents d\'expédition',
    search_documents: 'Rechercher des documents...',
    all_documents: 'Tous les documents',
    invoices: 'Factures',
    customs_declarations: 'Déclarations douanières',
    bills_of_lading: 'Connaissements',
    certificates: 'Certificats',
    other_documents: 'Autres documents',
    document: 'Document',
    shipment: 'Expédition',
    type: 'Type',
    uploaded: 'Téléchargé',
    actions: 'Actions',
    no_documents_found: 'Aucun document trouvé',
    no_documents_match_filters: 'Aucun document ne correspond à vos filtres actuels.',
    clear_filters: 'Effacer les filtres',
    upload_document: 'Télécharger un document',
    showing_documents: (params: { count: number }) => `Affichage de ${params.count} ${params.count === 1 ? 'document' : 'documents'}`,
    filtered: '(filtré)',
    location: 'Emplacement',
    invoice: 'Facture',
    bill_of_lading: 'Connaissement',
    certificate: 'Certificat',
    other_document: 'Autre document',
    shipment_type: 'Type d\'expédition',
    air_shipment: 'Fret aérien',
    sea_shipment: 'Fret maritime',
    type_air: 'Aérien',
    type_sea: 'Maritime',
    shipments_found: 'Expéditions trouvées',
    shipment_found: 'Expédition trouvée',
    overview: 'Aperçu',
    analytics: 'Analyses',
    delivery_performance: 'Performance de livraison',
    avg_delivery_time: 'Temps de livraison moyen',
    days: 'jours',
    on_time_delivery: 'Livraison à temps',
    delayed_shipments: 'Expéditions retardées',
    cancelled: 'Annulées',
    shipping_destinations: 'Destinations d\'expédition',
    other: 'Autre',
    recent_activity: 'Activité récente',
    no_recent_activity: 'Aucune activité récente',
    last_12_months: 'Les 12 derniers mois',
    try_adjusting_filters: 'Essayez d\'ajuster vos filtres ou critères de recherche',
    no_shipments_found: 'Aucune expédition trouvée',
    update_personal_information: 'Mettre à jour vos informations personnelles',
    notification_settings: 'Paramètres de notification',
    manage_how_we_contact_you: 'Gérez la façon dont nous vous contactons',
    password: 'Mot de passe',
    last_changed: 'Dernière modification',
    months_ago: 'mois',
    connected_devices: 'Appareils connectés',
    last_updated: 'Dernière mise à jour',
    manage_security_settings: 'Gérer vos paramètres de sécurité',
    customize_your_experience: 'Personnalisez votre expérience',
    back: 'Retour',
    download_all: 'Télécharger tout',
    shipment_details: 'Détails de l\'expédition',
    additional_information: 'Informations supplémentaires',
    incoterms: 'Incoterms',
    containers: 'Conteneurs',
    insurance: 'Assurance',
    customs_status: 'Statut douanier',
    parties: 'Parties',
    shipper: 'Expéditeur',
    consignee: 'Destinataire',
    claim: 'Déposer une réclamation',
    contact_information: 'Coordonnées',
    account_manager: 'Responsable de compte',
    agent_in_charge: 'Agent en charge',
    user_identifier: 'identifiant',
    contact_agent: 'Contacter l\'agent',
    shipment_reference: 'Référence d\'expédition',
    message: 'Message',
    write_your_message_here: 'Écrivez votre message ici...',
    send_message: 'Envoyer le message',
    sending: 'Envoi en cours...',
    message_sent_successfully: 'Message envoyé avec succès',
    available: 'Disponible',
    department: 'Département',
    position: 'Poste',
    languages: 'Langues',
    availability: 'Disponibilité',
    file_claim: 'Déposer une réclamation',
    claim_type: 'Type de réclamation',
    select_claim_type: 'Sélectionner un type de réclamation',
    write_your_claim_here: 'Écrivez les détails de votre réclamation ici...',
    submit_claim: 'Soumettre la réclamation',
    claim_sent_successfully: 'Réclamation envoyée avec succès',
    claim_agent_notification: 'Votre réclamation sera envoyée à l\'agent en charge et à son superviseur. Nous traiterons votre demande dans les plus brefs délais.',
    request_agent_change: 'Demande de changement d\'agent',
    delivery_issue: 'Problème de livraison',
    damaged_goods: 'Marchandises endommagées',
    missing_items: 'Articles manquants',
    customs_issue: 'Problème de douane',
    delay_complaint: 'Plainte pour retard',
    billing_issue: 'Problème de facturation',
    current_password: 'Mot de passe actuel',
    new_password: 'Nouveau mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    saving: 'Enregistrement...',
    security_requirements: 'Exigences de sécurité',
    password_req_length: 'Au moins 8 caractères',
    password_req_uppercase: 'Une lettre majuscule',
    password_req_lowercase: 'Une lettre minuscule',
    password_req_number: 'Un chiffre',
    password_req_special: 'Un caractère spécial',
    password_change_instruction: 'Utilisez un mot de passe fort que vous n\'utilisez sur aucun autre site.',
    error_current_password_required: 'Le mot de passe actuel est requis',
    error_password_requirements: 'Votre mot de passe ne respecte pas toutes les exigences',
    error_passwords_dont_match: 'Les mots de passe ne correspondent pas',
    password_changed_successfully: 'Mot de passe modifié avec succès',
    login: 'Se connecter',
    forgotPassword: 'Mot de passe oublié?',
    rememberMe: 'Se souvenir de moi',
    demoAccounts: 'Comptes de démonstration',
    allRightsReserved: '© 2025 ShipTrack. Tous droits réservés.',
    portal: 'Portail de suivi logistique',
    invalidCredentials: 'Identifiants invalides. Veuillez réessayer.',
    emailPlaceholder: 'vous@example.com',
    language: 'Langue',
    english: 'Anglais',
    french: 'Français',
    resetPassword: 'Réinitialiser le mot de passe',
    resetPasswordInstructions: 'Entrez votre e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
    sendResetLink: 'Envoyer le lien',
    resetEmailSent: 'E-mail envoyé',
    resetEmailSentDetails: 'Vérifiez votre boîte de réception pour un lien de réinitialisation de mot de passe. Si vous ne le voyez pas, vérifiez votre dossier de spam.',
    resetEmailError: 'Échec de l\'envoi de l\'e-mail de réinitialisation. Veuillez réessayer.',
    backToLogin: 'Retour à la connexion',
    createNewPassword: 'Créer un nouveau mot de passe',
    createNewPasswordInstructions: 'Votre mot de passe doit être différent des mots de passe précédents.',
    newPassword: 'Nouveau mot de passe',
    newPasswordPlaceholder: 'Entrez un nouveau mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordRequirementsNotMet: 'Le mot de passe ne répond pas à toutes les exigences',
    resetting: 'Réinitialisation...',
    passwordResetSuccess: 'Mot de passe mis à jour',
    passwordResetSuccessDetails: 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    proceedToLogin: 'Procéder à la connexion',
    invalidResetToken: 'Jeton de réinitialisation invalide ou expiré. Veuillez demander un nouveau lien de réinitialisation.',
    minLength: 'Au moins 8 caractères',
    upperCase: 'Au moins 1 lettre majuscule',
    lowerCase: 'Au moins 1 lettre minuscule',
    number: 'Au moins 1 chiffre',
    specialChar: 'Au moins 1 caractère spécial',
    new_message_instruction: 'Sélectionnez une expédition et rédigez votre message. Votre demande sera envoyée à l\'agent assigné.',
    select_shipment: 'Sélectionner une expédition',
    select_a_shipment: '-- Sélectionner une expédition --',
    subject: 'Sujet',
    enter_subject: 'Entrer un sujet',
    assigned_agent: 'Agent assigné',
    write_your_message: 'Écrivez votre message...',
    error_select_shipment: 'Veuillez sélectionner une expédition',
    error_message_required: 'Le message est requis',
    inquiry_about: 'Demande concernant',
    away: 'Absent',
    offline: 'Hors ligne',
    files_attached: 'Fichier joint',
    attached_files: 'Fichiers joints',    
    filters: 'filtres',
    manage_invoices: 'Gérez toutes vos factures',
    all_read: "Tout lu",
    no_unread_notifications: "Aucune notification non lue",
    dismiss: "Fermer",
    // Agent-specific translations
    transit_files: 'Dossiers de Transit',
    clients: 'Clients',
    client_management: 'Gestion des Clients',
    manage_client_portfolio: 'Gérez votre portefeuille clients et leurs informations',
    new_client: 'Nouveau client',
    create_client: 'Créer un client',
    new_file: 'Nouveau dossier',
    export: 'Exporter',
    manage_transit_files: 'Gérez tous vos dossiers de transit et expéditions',
    files_found: 'dossiers trouvés',
    file_found: 'dossier trouvé',
    no_files_found: 'Aucun dossier trouvé',
    no_files_match_filters: 'Aucun dossier ne correspond à vos critères de recherche.',
    clear_all_filters: 'Effacer les filtres',
    sort_by: 'Trier par',
    reference: 'Référence',
    client: 'Client',
    assigned_to: 'Assigné à',
    creation_date: 'Date de création',
    creation_date_from: 'Date de création (de)',
    creation_date_to: 'Date de création (à)',
    all_statuses: 'Tous les statuts',
    all_types: 'Tous les types',
    all_clients: 'Tous les clients',
    all_agents: 'Tous les agents',
    air: 'Aérien',
    sea: 'Maritime',
    transport_type: 'Type de transport',
    active_filters: 'Filtres actifs',
    search: 'Recherche',
    filter_by: 'Filtrer par',
    clear: 'Effacer',
    view_details: 'Voir détails',
    edit: 'Modifier',
    company: 'Entreprise',
    phone: 'Téléphone',
    city: 'Ville',
    country: 'Pays',
    active: 'Actif',
    inactive: 'Inactif',
    no_clients_found: 'Aucun client trouvé',
    no_clients_match_filters: 'Aucun client ne correspond à vos critères de recherche.',
    agent_dashboard: 'Tableau de bord Agent',
    manage_files_clients: 'Gérez vos dossiers de transit et clients',
    files: 'dossiers',
    found: 'trouvé',
    no_files_available: 'Aucun dossier de transit disponible pour le moment.',
    staff: 'Personnel',
    agent: 'Agent',
    manageFilesAndClients: 'Gérez vos dossiers de transit et clients',
    createClient: 'Créer un client',
    newFile: 'Nouveau dossier',
    searchPlaceholder: 'Rechercher par référence, origine, destination...',
    clearAll: 'Tout effacer',
    allStatuses: 'Tous les statuts',
    transportType: 'Type de transport',
    allTypes: 'Tous les types',
    allClients: 'Tous les clients',
    assignedTo: 'Assigné à',
    allAgents: 'Tous les agents',
    cityCountryPlaceholder: 'Ville, pays...',
    creationDateFrom: 'Date de création (du)',
    creationDateTo: 'Date de création (au)',
    activeFilters: 'Filtres actifs :',
    filesFound: 'dossier(s) trouvé(s)',
    sortBy: 'Trier par :',
    creationDate: 'Date de création',
    noFilesFound: 'Aucun dossier trouvé',
    noFilesFoundMessage: 'Aucun dossier ne correspond à vos critères de recherche.',
    noFilesAvailable: 'Aucun dossier de transit disponible pour le moment.',
    clearFilters: 'Réinitialiser les filtres',
    operations: 'Opérations',
    finance: 'Finances',
    itemsPerPage: 'éléments par page',
    view: 'Voir',
    of: 'sur',
    searchAgent: 'Recherche Agent',
    searchClient: 'Recherche Client',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}