import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    shipments: 'My Shipments',
    documents: 'Documents',
    messages: 'Messages',
    payments: 'Payments',
    profile: 'Profile',
    settings: 'Settings',
    signOut: 'Sign out',
    welcome: 'Welcome back',
    notifications: 'Notifications',
    support: 'Need assistance?',
    contactSupport: 'Contact Support',
    inTransit: 'In Transit',
    inWarehouse: 'In Warehouse',
    totalShipments: 'Total Shipments',
    issues: 'Issues',
    activeShipments: 'Active Shipments',
    viewAll: 'View all',
    recentActivity: 'Recent Activity',
    noActiveShipments: 'You don\'t have any active shipments at the moment.',
    updatedOn: 'Updated on',
    from: 'From',
    to: 'To',
    weight: 'Weight',
    volume: 'Volume',
    status: 'Status',
    origin: 'Origin',
    destination: 'Destination',
    description: 'Description',
    estimatedDelivery: 'Estimated Delivery',
    pending: 'Pending',
    draft: 'Draft',
    processing: 'Processing',
    customs: 'Customs Clearance',
    delivered: 'Delivered',
    issue: 'Issue',
    statsInTransit: 'In Transit',
    statsInWarehouse: 'In Warehouse',
    statsTotalShipments: 'Total Shipments',
    statsIssues: 'Issues',
    hereIsOverview: 'Here\'s an overview of your shipments',
    in_transit:'In Transit',
    warehouse: 'In Warehouse',
    all: 'All',
    created_at: 'Created on',
    shipment_timeLine: 'Shipment Timeline',
    in_customs_clearance: 'In Customs Clearance',
    shipment_created: 'Shipment Created',
    processing_started: 'Processing Started',
    arrived_at_warehouse: 'Arrived at Warehouse',
    delivered_successfully: 'Delivered Successfully',
    issue_reported: 'Issue Reported',
    my_shipments: 'My Shipments',
    search_shipments: 'Search shipments...',
    filter_by_status: 'Filter by Status',
    track_the_progress: 'Track the progress of your shipment',
    download: 'Download',
    no_documents_yet: 'No documents available yet.',
    quick_actions: 'Quick Actions',
    contact_the_agent_in_charge: 'Contact the agent in charge',
    notifications_description: 'Stay updated with your shipment status and important alerts',
    all_notifications: 'All Notifications',
    unread_count: (params: { count: number }) => `You have ${params.count} unread notifications`,
    mark_all_as_read: 'Mark all as read',
    no_notifications: 'No notifications',
    no_notifications_description: 'You\'re all caught up! No new notifications at the moment.',
    view_all_notifications: 'View all notifications',
    view_profile_analytics: 'View your profile and shipping analytics',
    member_since: 'Member since',
    completion_rate: 'Completion Rate',
    active_shipments: 'Active Shipments',
    completed: 'Completed',
    monthly_shipments: 'Monthly Shipments',
    shipment_status_distribution: 'Shipment Status Distribution',
    manage_account_preferences: 'Manage your account preferences',
    change_avatar: 'Change avatar',
    name: 'Name',
    email: 'Email',
    preferences: 'Preferences',
    language_preference: 'Language',
    email_notifications: 'Email notifications',
    receive_notifications: 'Receive notifications about your shipments',
    security: 'Security',
    change_password: 'Change password',
    cancel: 'Cancel',
    save_changes: 'Save changes',
    tracking_number: 'Tracking #',
    my_invoices: 'My Invoices',
    invoice_number: 'Invoice Number',
    amount: 'Amount',
    due_date: 'Due Date',
    payment_status: 'Payment Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    search_invoices: 'Search invoices...',
    filter_by_payment_status: 'Filter by Payment Status',
    total_paid: 'Total Paid',
    total_unpaid: 'Total Unpaid',
    total_overdue: 'Total Overdue',
    pay_now: 'Pay Now',
    view_invoice: 'View Invoice',
    download_invoice: 'Download Invoice',
    invoice_date: 'Invoice Date',
    payment_due: 'Payment Due',
    payment_received: 'Payment Received',
    invoice_details: 'Invoice Details',
    manage_messages: 'Manage your shipment communications',
    new_message: 'New Message',
    new: 'New',
    search_messages: 'Search messages...',
    no_conversations: 'No conversations match your search',
    online: 'Online',
    write_message: 'Write your message...',
    send: 'Send',
    today: 'Today',
    yesterday: 'Yesterday',
    view_profile: 'View Profile',
    mark_as_read: 'Mark as read',
    attach_file: 'Attach file',
    show_less: 'Show Less',
    show_all: 'Show All',
    loading: 'Loading...',
    manage_documents: 'Manage all your shipment documents',
    search_documents: 'Search documents...',
    all_documents: 'All Documents',
    invoices: 'Invoices',
    customs_declarations: 'Customs Declarations',
    bills_of_lading: 'Bills of Lading',
    certificates: 'Certificates',
    other_documents: 'Other Documents',
    document: 'Document',
    shipment: 'Shipment',
    type: 'Type',
    uploaded: 'Uploaded',
    actions: 'Actions',
    no_documents_found: 'No documents found',
    no_documents_match_filters: 'No documents match your current filters.',
    clear_filters: 'Clear filters',
    upload_document: 'Upload Document',
    showing_documents: (params: { count: number }) => `Showing ${params.count} ${params.count === 1 ? 'document' : 'documents'}`,
    filtered: '(filtered)',
    location: 'Location',
    invoice: 'Invoice',
    bill_of_lading: 'Bill of Lading',
    certificate: 'Certificate',
    other_document: 'Other Document',
    shipment_type: 'Shipment Type',
    air_shipment: 'Air Freight',
    sea_shipment: 'Sea Freight',
    type_air: 'Air',
    type_sea: 'Sea',
    shipments_found: 'Shipments found',
    shipment_found: 'Shipment found',
    overview: 'Overview',
    analytics: 'Analytics',
    delivery_performance: 'Delivery Performance',
    avg_delivery_time: 'Average Delivery Time',
    days: 'days',
    on_time_delivery: 'On-time Delivery',
    delayed_shipments: 'Delayed Shipments',
    cancelled: 'Cancelled',
    shipping_destinations: 'Shipping Destinations',
    other: 'Other',
    recent_activity: 'Recent Activity',
    no_recent_activity: 'No recent activity',
    last_12_months: 'Last 12 months',
    try_adjusting_filters: 'Try adjusting your filters or search criteria',
    no_shipments_found: 'No shipments found',
    update_personal_information: 'Update your personal information',
    notification_settings: 'Notification settings',
    manage_how_we_contact_you: 'Manage how we contact you',
    password: 'Password',
    last_changed: 'Last changed',
    months_ago: 'months ago',
    connected_devices: 'Connected devices',
    last_updated: 'Last updated',
    manage_security_settings: 'Manage your security settings',
    customize_your_experience: 'Customize your experience',
    back: 'Back',
    download_all: 'Download all',
    shipment_details: 'Shipment Details',
    additional_information: 'Additional Information',
    incoterms: 'Incoterms',
    containers: 'Containers',
    insurance: 'Insurance',
    customs_status: 'Customs Status',
    parties: 'Parties',
    shipper: 'Shipper',
    consignee: 'Consignee',
    claim: 'Claim',
    contact_information: 'Contact Information',
    account_manager: 'Account Manager',
    agent_in_charge: 'Agent in charge',
    user_identifier: 'identifier',
    contact_agent: 'Contact agent',
    shipment_reference: 'Shipment reference',
    message: 'Message',
    write_your_message_here: 'Write your message here...',
    send_message: 'Send message',
    sending: 'Sending...',
    message_sent_successfully: 'Message sent successfully',
    available: 'Available',
    department: 'Department',
    position: 'Position',
    languages: 'Languages',
    availability: 'Availability',
    file_claim: 'File a Claim',
    claim_type: 'Claim Type',
    select_claim_type: 'Select claim type',
    write_your_claim_here: 'Write your claim details here...',
    submit_claim: 'Submit Claim',
    claim_sent_successfully: 'Claim sent successfully',
    claim_agent_notification: 'Your claim will be sent to the agent in charge and their supervisor. We will process your request as soon as possible.',
    request_agent_change: 'Request Agent Change',
    delivery_issue: 'Delivery Issue',
    damaged_goods: 'Damaged Goods',
    missing_items: 'Missing Items',
    customs_issue: 'Customs Issue',
    delay_complaint: 'Delay Complaint',
    billing_issue: 'Billing Issue',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    saving: 'Saving...',
    security_requirements: 'Security Requirements',
    password_req_length: 'At least 8 characters',
    password_req_uppercase: 'One uppercase letter',
    password_req_lowercase: 'One lowercase letter',
    password_req_number: 'One number',
    password_req_special: 'One special character',
    password_change_instruction: 'Use a strong password that you don\'t use on any other site.',
    error_current_password_required: 'Current password is required',
    error_password_requirements: 'Your password doesn\'t meet all requirements',
    error_passwords_dont_match: 'Passwords don\'t match',
    password_changed_successfully: 'Password changed successfully',
    login: 'Log in',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    demoAccounts: 'Demo accounts',
    allRightsReserved: '© 2025 ShipTrack. All rights reserved.',
    portal: 'Logistics tracking portal',
    invalidCredentials: 'Invalid credentials. Please try again.',
    emailPlaceholder: 'you@example.com',
    language: 'Language',
    english: 'English',
    french: 'French',
    resetPassword: 'Reset Password',
    resetPasswordInstructions: 'Enter your email and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send reset link',
    resetEmailSent: 'Email sent',
    resetEmailSentDetails: 'Check your inbox for a link to reset your password. If you don\'t see it, check your spam folder.',
    resetEmailError: 'Failed to send reset email. Please try again.',
    backToLogin: 'Back to login',
    createNewPassword: 'Create New Password',
    createNewPasswordInstructions: 'Your password must be different from previous passwords.',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Enter new password',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Confirm your password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordRequirementsNotMet: 'Password does not meet all requirements',
    resetting: 'Resetting...',
    passwordResetSuccess: 'Password updated',
    passwordResetSuccessDetails: 'Your password has been reset successfully. You can now login with your new password.',
    proceedToLogin: 'Proceed to login',
    invalidResetToken: 'Invalid or expired reset token. Please request a new reset link.',
    minLength: 'At least 8 characters',
    upperCase: 'At least 1 uppercase letter',
    lowerCase: 'At least 1 lowercase letter',
    number: 'At least 1 number',
    specialChar: 'At least 1 special character',
    new_message_instruction: 'Select a shipment and write your message. Your inquiry will be sent to the assigned agent.',
    select_shipment: 'Select Shipment',
    select_a_shipment: '-- Select a shipment --',
    subject: 'Subject',
    enter_subject: 'Enter subject',
    assigned_agent: 'Assigned Agent',
    write_your_message: 'Write your message...',
    error_select_shipment: 'Please select a shipment',
    error_message_required: 'Message is required',
    inquiry_about: 'Inquiry about',
    away: 'Away',
    offline: 'Offline',
    files_attached: 'Files attached',
    attached_files: 'Attached files',    
    filters: 'filters',
    manage_invoices: 'Manage all your invoices',
    all_read: "All read",
    no_unread_notifications: "No unread notifications",
    dismiss: "Dismiss",
    // Container management translations
    containers: 'Containers',
    add_container: 'Add Container',
    edit_container: 'Edit Container',
    update_container: 'Update Container',
    container_number: 'Container Number',
    container_type: 'Container Type',
    container_size: 'Container Size',
    dry_container: 'Dry Container',
    refrigerated_container: 'Refrigerated Container',
    open_top_container: 'Open Top Container',
    flat_rack_container: 'Flat Rack Container',
    tank_container: 'Tank Container',
    other_container: 'Other Container',
    no_containers_added: 'No containers added yet',
    add_first_container: 'Add your first container',
    container_number_format: 'Format: 4 letters + 7 digits (e.g., ABCD1234567)',
    invalid_container_number_format: 'Invalid format. Use 4 letters + 7 digits',
    invalid_volume: 'Please enter a valid volume',
    invalid_weight: 'Please enter a valid weight',
    container_number_already_exists: 'This container number already exists',
    container: 'container',
    containers: 'containers',
    // Agent-specific translations
    transit_files: 'Transit Files',
    clients: 'Clients',
    client_management: 'Client Management',
    manage_client_portfolio: 'Manage your client portfolio and their information',
    new_client: 'New Client',
    create_client: 'Create Client',
    new_file: 'New File',
    export: 'Export',
    manage_transit_files: 'Manage all your transit files and shipments',
    new_transit_file: 'New Transit File',
    create_transit_file: 'Create Transit File',
    bl_number: 'BL/LTA/Route Sheet Number',
    file_reference: 'File Reference',
    transport_type: 'Transport Type',
    product_type: 'Product Type',
    standard: 'Standard',
    dangerous: 'Dangerous',
    fragile: 'Fragile',
    sea_freight: 'Sea Freight',
    air_freight: 'Air Freight',
    maritime: 'Maritime',
    aerial: 'Aerial',
    shipment_type: 'Shipment Type',
    import: 'Import',
    export: 'Export',
    add_clients: 'Add Clients',
    selected_clients: 'Selected Clients',
    route_and_capacity: 'Route and Capacity',
    capacity: 'Capacity',
    content_description: 'Content Description',
    invoice: 'Invoice',
    packing_list: 'Packing List',
    other_documents: 'Other Documents',
    uploaded_files: 'Uploaded Files',
    make_private: 'Make Private',
    make_public: 'Make Public',
    private: 'Private',
    public: 'Public',
    system_information: 'System Information',
    agent_in_charge: 'Agent in Charge',
    creation_date: 'Creation Date',
    creating: 'Creating...',
    create_file: 'Create File',
    transit_file_created: 'Transit File Created Successfully!',
    transit_file_created_desc: 'The new transit file has been created and added to your portfolio.',
    back_to_dashboard: 'Back to Dashboard',
    view_file: 'View File',
    general_information: 'General Information',
    enter_bl_number: 'Enter BL number',
    search_client: 'Search for a client...',
    city_country: 'City, country',
    capacity_example: 'Ex: 20 feet, 1000 kg, 50 m³',
    describe_content: 'Describe the file content...',
    files_found: 'files found',
    file_found: 'file found',
    no_files_found: 'No files found',
    no_files_match_filters: 'No files match your current search criteria.',
    clear_all_filters: 'Clear all filters',
    sort_by: 'Sort by',
    reference: 'Reference',
    client: 'Client',
    assigned_to: 'Assigned to',
    creation_date: 'Creation date',
    creation_date_from: 'Creation date (from)',
    creation_date_to: 'Creation date (to)',
    all_statuses: 'All statuses',
    all_types: 'All types',
    all_clients: 'All clients',
    all_agents: 'All agents',
    air: 'Air',
    sea: 'Sea',
    transport_type: 'Transport type',
    active_filters: 'Active filters',
    search: 'Search',
    filter_by: 'Filter by',
    clear: 'Clear',
    view_details: 'View details',
    edit: 'Edit',
    company: 'Company',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    active: 'Active',
    inactive: 'Inactive',
    no_clients_found: 'No clients found',
    no_clients_match_filters: 'No clients match your current search criteria.',
    agent_dashboard: 'Agent Dashboard',
    manage_files_clients: 'Manage your transit files and clients',
    files: 'Files',
    found: 'found',
    no_files_available: 'No transit files available at the moment.',
    staff: 'Staff',
    declarations: 'Declarations',
    agent: 'Agent',
    manageFilesAndClients: 'Manage your transit files and clients',
    createClient: 'Create Client',
    newFile: 'New File',
    searchPlaceholder: 'Search by reference, origin, destination...',
    clearAll: 'Clear All',
    allStatuses: 'All Statuses',
    transportType: 'Transport Type',
    allTypes: 'All Types',
    allClients: 'All Clients',
    assignedTo: 'Assigned To',
    allAgents: 'All Agents',
    cityCountryPlaceholder: 'City, country...',
    creationDateFrom: 'Creation Date (From)',
    creationDateTo: 'Creation Date (To)',
    activeFilters: 'Active filters:',
    filesFound: 'file(s) found',
    sortBy: 'Sort by:',
    creationDate: 'Creation Date',
    noFilesFound: 'No Files Found',
    noFilesFoundMessage: 'No files match your search criteria.',
    noFilesAvailable: 'No transit files available at the moment.',
    clearFilters: 'Clear Filters',
    operations: 'Operations',
    finance: 'Finance',
    itemsPerPage: 'Items per page',
    view: 'View',
    of: 'of',
    searchAgent: 'Search Agent',
    searchClient: 'Search Client',
    noClientsFound: 'No clients found',
    noAgentsFound: 'No agents found',
    save: 'Save',
    newClient: 'New Client',
    createNewClient: 'Create a new client',
    clientInformation: 'Client Information',
    personalInfo: 'Personal Information',
    contactInfo: 'Contact Information',
    companyInfo: 'Company Information',
    addressInfo: 'Address Information',
    systemInfo: 'System Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    avatar: 'Profile Picture',
    clientId: 'Client ID',
    assignedAgent: 'Assigned Agent',
    required: 'This field is required',
    invalidEmail: 'Invalid email',
    clientCreated: 'Client created successfully!',
    clientCreatedDesc: 'The new client has been added to your portfolio.',
    backToClients: 'Back to clients',
    viewClient: 'View client',
    fillAllFields: 'Please fill in all required fields',
    firstNamePlaceholder: 'Enter first name',
    lastNamePlaceholder: 'Enter last name',
    phonePlaceholder: '+221 77 111 22 33',
    companyPlaceholder: 'Company name',
    addressPlaceholder: 'Full address',
    cityPlaceholder: 'City',
    countryPlaceholder: 'Country',
    unknown_client: 'Unknown Client',
    visibility: 'Visibility',
    aerial: 'Aerial',
    creating: 'Creating...',
    client_visible: 'Client visible',
    file_visibility_settings: 'File visibility settings',
    // Edit client specific translations
    edit_client: 'Edit Client',
    edit_client_desc: 'Edit client information',
    client_updated: 'Client Updated Successfully',
    client_updated_desc: 'The client information has been updated successfully.',
    client_not_found: 'Client Not Found',
    client_not_found_desc: 'The requested client does not exist or has been deleted.',
    // Tab content translations
    basic_information: 'Basic Information',
    client_statistics: 'Client Statistics',
    total_shipments: 'Total Shipments',
    success_rate: 'Success Rate',
    average_delivery_time: 'Average Delivery Time',
    pending_shipments: 'Pending Shipments',
    recent_shipments: 'Recent Shipments',
    no_shipments_for_client: 'No shipments found for this client',
    client_documents: 'Client Documents',
    document_management: 'Document management will be available soon.',
    activity_log: 'Activity Log',
    activity_management: 'Activity history will be available soon.',
    address: 'Address',
    client_since: 'Client since',
    last_activity: 'Last activity',
    total_value: 'Total value',
    average_shipment_value: 'Average shipment value',
    preferred_routes: 'Preferred routes',
    shipment_history: 'Shipment History',
    filter_shipments: 'Filter shipments',
    all_shipment_statuses: 'All statuses',
    search_shipments_placeholder: 'Search shipments...',
    no_shipments_match_criteria: 'No shipments match your criteria.',
    clear_shipment_filters: 'Clear filters',
    // Client details specific translations
    client_details: 'Client Details',
    client_profile: 'Client Profile',
    contact_client: 'Contact Client',
    modify_client: 'Modify Client',
    client_information: 'Client Information',
    business_metrics: 'Business Metrics',
    performance_overview: 'Performance Overview',
    shipment_volume: 'Shipment Volume',
    revenue_generated: 'Revenue Generated',
    average_transit_time: 'Average Transit Time',
    customer_satisfaction: 'Customer Satisfaction',
    monthly_volume: 'Monthly Volume',
    yearly_growth: 'Yearly Growth',
    preferred_shipping_methods: 'Preferred Shipping Methods',
    top_destinations: 'Top Destinations',
    document_compliance: 'Document Compliance',
    payment_history: 'Payment History',
    communication_log: 'Communication Log',
    service_requests: 'Service Requests',
    contract_details: 'Contract Details',
    billing_information: 'Billing Information',
    emergency_contacts: 'Emergency Contacts',
    special_instructions: 'Special Instructions',
    risk_assessment: 'Risk Assessment',
    credit_rating: 'Credit Rating',
    insurance_coverage: 'Insurance Coverage',
    compliance_status: 'Compliance Status',
    last_contact: 'Last Contact',
    next_review: 'Next Review',
    account_status: 'Account Status',
    relationship_manager: 'Relationship Manager',
    onboarding_date: 'Onboarding Date',
    contract_expiry: 'Contract Expiry',
    renewal_date: 'Renewal Date',
    payment_terms: 'Payment Terms',
    credit_limit: 'Credit Limit',
    outstanding_balance: 'Outstanding Balance',
    last_payment: 'Last Payment',
    payment_method: 'Payment Method',
    billing_address: 'Billing Address',
    tax_information: 'Tax Information',
    document_uploaded: 'Document uploaded',
    status_updated: 'Status updated',
    meeting_scheduled: 'Meeting scheduled',
    contract_renewed: 'Contract renewed',
    issue_resolved: 'Issue resolved',
    feedback_received: 'Feedback received',
    by: 'by',
    ago: 'ago',
    minutes: 'minutes',
    hours: 'hours',
    weeks: 'weeks',
    months: 'months',
    years: 'years',
    contract: 'Contract',
    insurance_policy: 'Insurance Policy',
    tax_certificate: 'Tax Certificate',
    compliance_document: 'Compliance Document',
    financial_statement: 'Financial Statement',
    size: 'Size',
    download_document: 'Download document',
    view_document: 'View document',
    document_details: 'Document details',
    no_documents_available: 'No documents available for this client.',
    upload_new_document: 'Upload new document',
    document_type: 'Document type',
    file_size: 'File size',
    upload_date: 'Upload date',
    uploaded_by: 'Uploaded by',
    document_status: 'Document status',
    approved: 'Approved',
    pending_review: 'Pending Review',
    rejected: 'Rejected',
    expired: 'Expired',
  },
  fr: {
    dashboard: 'Tableau de bord',
    shipments: 'Mes expéditions',
    documents: 'Documents',
    messages: 'Messages',
    payments: 'Paiements',
    profile: 'Profil',
    settings: 'Paramètres',
    signOut: 'Déconnexion',
    welcome: 'Bienvenue',
    notifications: 'Notifications',
    support: 'Besoin d\'aide ?',
    contactSupport: 'Contacter le support',
    inTransit: 'En transit',
    inWarehouse: 'En entrepôt',
    totalShipments: 'Total des expéditions',
    issues: 'Problèmes',
    activeShipments: 'Expéditions actives',
    viewAll: 'Voir tout',
    recentActivity: 'Activité récente',
    noActiveShipments: 'Vous n\'avez aucune expédition active en ce moment.',
    updatedOn: 'Mis à jour le',
    from: 'De',
    to: 'Vers',
    weight: 'Poids',
    volume: 'Volume',
    status: 'Statut',
    origin: 'Origine',
    destination: 'Destination',
    description: 'Description',
    estimatedDelivery: 'Livraison estimée',
    pending: 'En attente',
    draft: 'Brouillon',
    processing: 'En traitement',
    customs: 'Dédouanement',
    delivered: 'Livré',
    issue: 'Problème',
    statsInTransit: 'En Transit',
    statsInWarehouse: 'En Entrepôt',
    statsTotalShipments: 'Total des Expéditions',
    statsIssues: 'Problèmes',
    hereIsOverview: 'Voici un aperçu de vos expéditions',
    in_transit:'En Transit',
    warehouse: 'En Entrepôt',
    all: 'Tout',
    created_at: 'Créé le',
    shipment_timeLine: 'Calendrier d\'expédition',
    in_customs_clearance: 'En dédouanement',
    shipment_created: 'Expédition créée',
    processing_started: 'Traitement démarré',
    arrived_at_warehouse: 'Arrivé à l\'entrepôt',
    delivered_successfully: 'Livré avec succès',
    issue_reported: 'Problème signalé',
    my_shipments: 'Mes Expéditions',
    search_shipments: 'Rechercher expédition...',
    filter_by_status: 'Filtre par statut',
    track_the_progress: 'Suivez la progression de votre envoi',
    download: 'Télécharger',
    no_documents_yet: 'Aucun document disponible pour le moment.',
    quick_actions: 'Actions rapides',
    contact_the_agent_in_charge: 'Contacter l\'agent en charge',
    notifications_description: 'Restez informé de l\'état de vos expéditions et des alertes importantes',
    all_notifications: 'Toutes les notifications',
    unread_count: (params: { count: number }) => `Vous avez ${params.count} notifications non lues`,
    mark_all_as_read: 'Tout marquer comme lu',
    no_notifications: 'Aucune notification',
    no_notifications_description: 'Vous êtes à jour ! Aucune nouvelle notification pour le moment.',
    view_all_notifications: 'Voir toutes les notifications',
    view_profile_analytics: 'Consultez votre profil et vos analyses d\'expédition',
    member_since: 'Membre depuis',
    completion_rate: 'Taux de réussite',
    active_shipments: 'Expéditions actives',
    completed: 'Terminées',
    monthly_shipments: 'Expéditions mensuelles',
    shipment_status_distribution: 'Distribution des statuts d\'expédition',
    manage_account_preferences: 'Gérez vos préférences de compte',
    change_avatar: 'Changer l\'avatar',
    name: 'Nom',
    email: 'Email',
    preferences: 'Préférences',
    language_preference: 'Langue',
    email_notifications: 'Notifications par email',
    receive_notifications: 'Recevoir des notifications concernant vos expéditions',
    security: 'Sécurité',
    change_password: 'Changer le mot de passe',
    cancel: 'Annuler',
    save_changes: 'Enregistrer les modifications',
    tracking_number: 'N° de suivi',
    my_invoices: 'Mes Factures',
    invoice_number: 'Numéro de facture',
    amount: 'Montant',
    due_date: 'Date d\'échéance',
    payment_status: 'Statut de paiement',
    paid: 'Payée',
    unpaid: 'Non payée',
    overdue: 'En retard',
    search_invoices: 'Rechercher des factures...',
    filter_by_payment_status: 'Filtrer par statut de paiement',
    total_paid: 'Total payé',
    total_unpaid: 'Total non payé',
    total_overdue: 'Total en retard',
    pay_now: 'Payer maintenant',
    view_invoice: 'Voir la facture',
    download_invoice: 'Télécharger la facture',
    invoice_date: 'Date de facturation',
    payment_due: 'Paiement dû',
    payment_received: 'Paiement reçu',
    invoice_details: 'Détails de la facture',
    manage_messages: 'Gérez vos communications d\'expédition',
    new_message: 'Nouveau message',
    new: 'Nouveau',
    search_messages: 'Rechercher messages...',
    no_conversations: 'Aucune conversation ne correspond à votre recherche',
    online: 'En ligne',
    write_message: 'Écrivez votre message...',
    send: 'Envoyer',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    view_profile: 'Voir le profil',
    mark_as_read: 'Marquer comme lu',
    attach_file: 'Joindre un fichier',
    show_less: 'Voir moins',
    show_all: 'Voir tout',
    loading: 'Chargement...',
    manage_documents: 'Gérez tous vos documents d\'expédition',
    search_documents: 'Rechercher des documents...',
    all_documents: 'Tous les documents',
    invoices: 'Factures',
    customs_declarations: 'Déclarations douanières',
    bills_of_lading: 'Connaissements',
    certificates: 'Certificats',
    other_documents: 'Autres documents',
    document: 'Document',
    shipment: 'Expédition',
    type: 'Type',
    uploaded: 'Téléchargé',
    actions: 'Actions',
    no_documents_found: 'Aucun document trouvé',
    no_documents_match_filters: 'Aucun document ne correspond à vos filtres actuels.',
    clear_filters: 'Effacer les filtres',
    upload_document: 'Télécharger un document',
    showing_documents: (params: { count: number }) => `Affichage de ${params.count} ${params.count === 1 ? 'document' : 'documents'}`,
    filtered: '(filtré)',
    location: 'Emplacement',
    invoice: 'Facture',
    bill_of_lading: 'Connaissement',
    certificate: 'Certificat',
    other_document: 'Autre document',
    shipment_type: 'Type d\'expédition',
    air_shipment: 'Fret aérien',
    sea_shipment: 'Fret maritime',
    type_air: 'Aérien',
    type_sea: 'Maritime',
    shipments_found: 'Expéditions trouvées',
    shipment_found: 'Expédition trouvée',
    overview: 'Aperçu',
    analytics: 'Analyses',
    delivery_performance: 'Performance de livraison',
    avg_delivery_time: 'Temps de livraison moyen',
    days: 'jours',
    on_time_delivery: 'Livraison à temps',
    delayed_shipments: 'Expéditions retardées',
    cancelled: 'Annulées',
    shipping_destinations: 'Destinations d\'expédition',
    other: 'Autre',
    recent_activity: 'Activité récente',
    no_recent_activity: 'Aucune activité récente',
    last_12_months: 'Les 12 derniers mois',
    try_adjusting_filters: 'Essayez d\'ajuster vos filtres ou critères de recherche',
    no_shipments_found: 'Aucune expédition trouvée',
    update_personal_information: 'Mettre à jour vos informations personnelles',
    notification_settings: 'Paramètres de notification',
    manage_how_we_contact_you: 'Gérez la façon dont nous vous contactons',
    password: 'Mot de passe',
    last_changed: 'Dernière modification',
    months_ago: 'mois',
    connected_devices: 'Appareils connectés',
    last_updated: 'Dernière mise à jour',
    manage_security_settings: 'Gérer vos paramètres de sécurité',
    customize_your_experience: 'Personnalisez votre expérience',
    back: 'Retour',
    download_all: 'Télécharger tout',
    shipment_details: 'Détails de l\'expédition',
    additional_information: 'Informations supplémentaires',
    incoterms: 'Incoterms',
    containers: 'Conteneurs',
    insurance: 'Assurance',
    customs_status: 'Statut douanier',
    parties: 'Parties',
    shipper: 'Expéditeur',
    consignee: 'Destinataire',
    claim: 'Déposer une réclamation',
    contact_information: 'Coordonnées',
    account_manager: 'Responsable de compte',
    agent_in_charge: 'Agent en charge',
    user_identifier: 'identifiant',
    contact_agent: 'Contacter l\'agent',
    shipment_reference: 'Référence d\'expédition',
    message: 'Message',
    write_your_message_here: 'Écrivez votre message ici...',
    send_message: 'Envoyer le message',
    sending: 'Envoi en cours...',
    message_sent_successfully: 'Message envoyé avec succès',
    available: 'Disponible',
    department: 'Département',
    position: 'Poste',
    languages: 'Langues',
    availability: 'Disponibilité',
    file_claim: 'Déposer une réclamation',
    claim_type: 'Type de réclamation',
    select_claim_type: 'Sélectionner un type de réclamation',
    write_your_claim_here: 'Écrivez les détails de votre réclamation ici...',
    submit_claim: 'Soumettre la réclamation',
    claim_sent_successfully: 'Réclamation envoyée avec succès',
    claim_agent_notification: 'Votre réclamation sera envoyée à l\'agent en charge et à son superviseur. Nous traiterons votre demande dans les plus brefs délais.',
    request_agent_change: 'Demande de changement d\'agent',
    delivery_issue: 'Problème de livraison',
    damaged_goods: 'Marchandises endommagées',
    missing_items: 'Articles manquants',
    customs_issue: 'Problème de douane',
    delay_complaint: 'Plainte pour retard',
    billing_issue: 'Problème de facturation',
    current_password: 'Mot de passe actuel',
    new_password: 'Nouveau mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    saving: 'Enregistrement...',
    security_requirements: 'Exigences de sécurité',
    password_req_length: 'Au moins 8 caractères',
    password_req_uppercase: 'Une lettre majuscule',
    password_req_lowercase: 'Une lettre minuscule',
    password_req_number: 'Un chiffre',
    password_req_special: 'Un caractère spécial',
    password_change_instruction: 'Utilisez un mot de passe fort que vous n\'utilisez sur aucun autre site.',
    error_current_password_required: 'Le mot de passe actuel est requis',
    error_password_requirements: 'Votre mot de passe ne respecte pas toutes les exigences',
    error_passwords_dont_match: 'Les mots de passe ne correspondent pas',
    password_changed_successfully: 'Mot de passe modifié avec succès',
    login: 'Se connecter',
    forgotPassword: 'Mot de passe oublié?',
    rememberMe: 'Se souvenir de moi',
    demoAccounts: 'Comptes de démonstration',
    allRightsReserved: '© 2025 ShipTrack. Tous droits réservés.',
    portal: 'Portail de suivi logistique',
    invalidCredentials: 'Identifiants invalides. Veuillez réessayer.',
    emailPlaceholder: 'vous@example.com',
    language: 'Langue',
    english: 'Anglais',
    french: 'Français',
    resetPassword: 'Réinitialiser le mot de passe',
    resetPasswordInstructions: 'Entrez votre e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
    sendResetLink: 'Envoyer le lien',
    resetEmailSent: 'E-mail envoyé',
    resetEmailSentDetails: 'Vérifiez votre boîte de réception pour un lien de réinitialisation de mot de passe. Si vous ne le voyez pas, vérifiez votre dossier de spam.',
    resetEmailError: 'Échec de l\'envoi de l\'e-mail de réinitialisation. Veuillez réessayer.',
    backToLogin: 'Retour à la connexion',
    createNewPassword: 'Créer un nouveau mot de passe',
    createNewPasswordInstructions: 'Votre mot de passe doit être différent des mots de passe précédents.',
    newPassword: 'Nouveau mot de passe',
    newPasswordPlaceholder: 'Entrez un nouveau mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordRequirementsNotMet: 'Le mot de passe ne répond pas à toutes les exigences',
    resetting: 'Réinitialisation...',
    passwordResetSuccess: 'Mot de passe mis à jour',
    passwordResetSuccessDetails: 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    proceedToLogin: 'Procéder à la connexion',
    invalidResetToken: 'Jeton de réinitialisation invalide ou expiré. Veuillez demander un nouveau lien de réinitialisation.',
    minLength: 'Au moins 8 caractères',
    upperCase: 'Au moins 1 lettre majuscule',
    lowerCase: 'Au moins 1 lettre minuscule',
    number: 'Au moins 1 chiffre',
    specialChar: 'Au moins 1 caractère spécial',
    new_message_instruction: 'Sélectionnez une expédition et rédigez votre message. Votre demande sera envoyée à l\'agent assigné.',
    select_shipment: 'Sélectionner une expédition',
    select_a_shipment: '-- Sélectionner une expédition --',
    subject: 'Sujet',
    enter_subject: 'Entrer un sujet',
    assigned_agent: 'Agent assigné',
    write_your_message: 'Écrivez votre message...',
    error_select_shipment: 'Veuillez sélectionner une expédition',
    error_message_required: 'Le message est requis',
    inquiry_about: 'Demande concernant',
    away: 'Absent',
    offline: 'Hors ligne',
    files_attached: 'Fichier joint',
    attached_files: 'Fichiers joints',    
    filters: 'filtres',
    manage_invoices: 'Gérez toutes vos factures',
    all_read: "Tout lu",
    no_unread_notifications: "Aucune notification non lue",
    dismiss: "Fermer",
    // Container management translations
    containers: 'Conteneurs',
    add_container: 'Ajouter un conteneur',
    edit_container: 'Modifier le conteneur',
    update_container: 'Mettre à jour le conteneur',
    container_number: 'Numéro de conteneur',
    container_type: 'Type de conteneur',
    container_size: 'Taille du conteneur',
    dry_container: 'Conteneur sec',
    refrigerated_container: 'Conteneur frigorifique',
    open_top_container: 'Conteneur open top',
    flat_rack_container: 'Conteneur flat rack',
    tank_container: 'Conteneur citerne',
    other_container: 'Autre conteneur',
    no_containers_added: 'Aucun conteneur ajouté',
    add_first_container: 'Ajouter votre premier conteneur',
    container_number_format: 'Format : 4 lettres + 7 chiffres (ex: ABCD1234567)',
    invalid_container_number_format: 'Format invalide. Utilisez 4 lettres + 7 chiffres',
    invalid_volume: 'Veuillez entrer un volume valide',
    invalid_weight: 'Veuillez entrer un poids valide',
    container_number_already_exists: 'Ce numéro de conteneur existe déjà',
    container: 'conteneur',
    containers: 'conteneurs',
    // Agent-specific translations
    transit_files: 'Dossiers de Transit',
    clients: 'Clients',
    client_management: 'Gestion des Clients',
    manage_client_portfolio: 'Gérez votre portefeuille clients et leurs informations',
    new_client: 'Nouveau client',
    create_client: 'Créer un client',
    new_file: 'Nouveau dossier',
    export: 'Exporter',
    manage_transit_files: 'Gérez tous vos dossiers de transit et expéditions',
    new_transit_file: 'Nouveau Dossier',
    create_transit_file: 'Créer un Dossier',
    bl_number: 'Numéro BL/LTA/Feuille de route',
    file_reference: 'Référence du dossier',
    transport_type: 'Type de transport',
    product_type: 'Type de produit',
    standard: 'Standard',
    dangerous: 'Dangereux',
    fragile: 'Fragile',
    sea_freight: 'Fret maritime',
    air_freight: 'Fret aérien',
    maritime: 'Maritime',
    aerial: 'Aérien',
    shipment_type: 'Type d\'expédition',
    import: 'Import',
    export: 'Export',
    add_clients: 'Ajouter des clients',
    selected_clients: 'Clients sélectionnés',
    route_and_capacity: 'Itinéraire et capacité',
    capacity: 'Capacité',
    content_description: 'Description du contenu',
    invoice: 'Facture',
    packing_list: 'Liste de colisage',
    other_documents: 'Autres documents',
    uploaded_files: 'Fichiers téléchargés',
    make_private: 'Rendre privé',
    make_public: 'Rendre public',
    private: 'Privé',
    public: 'Public',
    system_information: 'Informations système',
    agent_in_charge: 'Agent en charge',
    creation_date: 'Date de création',
    creating: 'Création...',
    create_file: 'Créer le dossier',
    transit_file_created: 'Dossier créé avec succès!',
    transit_file_created_desc: 'Le nouveau dossier de transit a été créé et ajouté à votre portefeuille.',
    back_to_dashboard: 'Retour au tableau de bord',
    view_file: 'Voir le dossier',
    general_information: 'Informations générales',
    enter_bl_number: 'Entrez le numéro BL',
    search_client: 'Rechercher un client...',
    city_country: 'Ville, pays',
    capacity_example: 'Ex: 20 pieds, 1000 kg, 50 m³',
    describe_content: 'Décrivez le contenu du dossier...',
    files_found: 'dossiers trouvés',
    file_found: 'dossier trouvé',
    no_files_found: 'Aucun dossier trouvé',
    no_files_match_filters: 'Aucun dossier ne correspond à vos critères de recherche.',
    clear_all_filters: 'Effacer les filtres',
    sort_by: 'Trier par',
    reference: 'Référence',
    client: 'Client',
    assigned_to: 'Assigné à',
    creation_date: 'Date de création',
    creation_date_from: 'Date de création (de)',
    creation_date_to: 'Date de création (à)',
    all_statuses: 'Tous les statuts',
    all_types: 'Tous les types',
    all_clients: 'Tous les clients',
    all_agents: 'Tous les agents',
    air: 'Aérien',
    sea: 'Maritime',
    transport_type: 'Type de transport',
    active_filters: 'Filtres actifs',
    search: 'Recherche',
    filter_by: 'Filtrer par',
    clear: 'Effacer',
    view_details: 'Voir détails',
    edit: 'Modifier',
    company: 'Entreprise',
    phone: 'Téléphone',
    city: 'Ville',
    country: 'Pays',
    active: 'Actif',
    inactive: 'Inactif',
    no_clients_found: 'Aucun client trouvé',
    no_clients_match_filters: 'Aucun client ne correspond à vos critères de recherche.',
    agent_dashboard: 'Tableau de bord Agent',
    manage_files_clients: 'Gérez vos dossiers de transit et clients',
    files: 'dossiers',
    found: 'trouvé',
    no_files_available: 'Aucun dossier de transit disponible pour le moment.',
    staff: 'Personnel',
    agent: 'Agent',
    manageFilesAndClients: 'Gérez vos dossiers de transit et clients',
    createClient: 'Créer un client',
    newFile: 'Nouveau dossier',
    searchPlaceholder: 'Rechercher par référence, origine, destination...',
    clearAll: 'Tout effacer',
    allStatuses: 'Tous les statuts',
    transportType: 'Type de transport',
    allTypes: 'Tous les types',
    allClients: 'Tous les clients',
    assignedTo: 'Assigné à',
    allAgents: 'Tous les agents',
    cityCountryPlaceholder: 'Ville, pays...',
    creationDateFrom: 'Date de création (du)',
    creationDateTo: 'Date de création (au)',
    activeFilters: 'Filtres actifs :',
    filesFound: 'dossier(s) trouvé(s)',
    sortBy: 'Trier par :',
    creationDate: 'Date de création',
    noFilesFound: 'Aucun dossier trouvé',
    noFilesFoundMessage: 'Aucun dossier ne correspond à vos critères de recherche.',
    noFilesAvailable: 'Aucun dossier de transit disponible pour le moment.',
    clearFilters: 'Réinitialiser les filtres',
    operations: 'Opérations',
    finance: 'Finances',
    itemsPerPage: 'éléments par page',
    view: 'Voir',
    of: 'sur',
    searchAgent: 'Recherche Agent',
    searchClient: 'Recherche Client',
    noClientsFound: 'Aucun client trouvé',
    noAgentsFound: 'Aucun agent trouvé',
    save: 'Enregistrer',
    newClient: 'Nouveau Client',
    createNewClient: 'Créer un nouveau client',
    clientInformation: 'Informations du client',
    personalInfo: 'Informations personnelles',
    contactInfo: 'Informations de contact',
    companyInfo: 'Informations de l\'entreprise',
    addressInfo: 'Informations d\'adresse',
    systemInfo: 'Informations système',
    firstName: 'Prénom',
    lastName: 'Nom',
    avatar: 'Photo de profil',
    clientId: 'Identifiant Client',
    assignedAgent: 'Agent en charge',
    required: 'Ce champ est requis',
    invalidEmail: 'Email invalide',
    clientCreated: 'Client créé avec succès!',
    clientCreatedDesc: 'Le nouveau client a été ajouté à votre portefeuille.',
    backToClients: 'Retour aux clients',
    viewClient: 'Voir le client',
    fillAllFields: 'Veuillez remplir tous les champs obligatoires',
    firstNamePlaceholder: 'Entrez le prénom',
    lastNamePlaceholder: 'Entrez le nom',
    phonePlaceholder: '+221 77 111 22 33',
    companyPlaceholder: 'Nom de l\'entreprise',
    addressPlaceholder: 'Adresse complète',
    cityPlaceholder: 'Ville',
    countryPlaceholder: 'Pays',
    unknown_client: 'Client inconnu',
    visibility: 'Visibilité',
    aerial: 'Aérien',
    creating: 'Création...',
    client_visible: 'Visible par le client',
    file_visibility_settings: 'Paramètres de visibilité des fichiers',
    // Edit client specific translations
    edit_client: 'Modifier le client',
    edit_client_desc: 'Modifiez les informations du client',
    client_updated: 'Client mis à jour avec succès',
    client_updated_desc: 'Les informations du client ont été mises à jour avec succès.',
    client_not_found: 'Client non trouvé',
    client_not_found_desc: 'Le client demandé n\'existe pas ou a été supprimé.',
    // Tab content translations
    basic_information: 'Informations de base',
    client_statistics: 'Statistiques du client',
    total_shipments: 'Total des expéditions',
    success_rate: 'Taux de réussite',
    average_delivery_time: 'Temps de livraison moyen',
    pending_shipments: 'Expéditions en attente',
    recent_shipments: 'Expéditions récentes',
    no_shipments_for_client: 'Aucune expédition trouvée pour ce client',
    client_documents: 'Documents du client',
    document_management: 'La gestion des documents sera disponible prochainement.',
    activity_log: 'Journal d\'activité',
    activity_management: 'L\'historique des activités sera disponible prochainement.',
    address: 'Adresse',
    client_since: 'Client depuis',
    last_activity: 'Dernière activité',
    total_value: 'Valeur totale',
    average_shipment_value: 'Valeur moyenne par expédition',
    preferred_routes: 'Routes préférées',
    shipment_history: 'Historique des expéditions',
    filter_shipments: 'Filtrer les expéditions',
    all_shipment_statuses: 'Tous les statuts',
    search_shipments_placeholder: 'Rechercher des expéditions...',
    no_shipments_match_criteria: 'Aucune expédition ne correspond à vos critères.',
    clear_shipment_filters: 'Effacer les filtres',
    // Client details specific translations
    client_details: 'Détails du client',
    client_profile: 'Profil du client',
    contact_client: 'Contacter le client',
    modify_client: 'Modifier le client',
    client_information: 'Informations du client',
    business_metrics: 'Métriques commerciales',
    performance_overview: 'Aperçu des performances',
    shipment_volume: 'Volume d\'expéditions',
    revenue_generated: 'Chiffre d\'affaires généré',
    average_transit_time: 'Temps de transit moyen',
    customer_satisfaction: 'Satisfaction client',
    monthly_volume: 'Volume mensuel',
    yearly_growth: 'Croissance annuelle',
    preferred_shipping_methods: 'Méthodes d\'expédition préférées',
    top_destinations: 'Principales destinations',
    document_compliance: 'Conformité documentaire',
    payment_history: 'Historique des paiements',
    communication_log: 'Journal de communication',
    service_requests: 'Demandes de service',
    contract_details: 'Détails du contrat',
    billing_information: 'Informations de facturation',
    emergency_contacts: 'Contacts d\'urgence',
    special_instructions: 'Instructions spéciales',
    risk_assessment: 'Évaluation des risques',
    credit_rating: 'Cote de crédit',
    insurance_coverage: 'Couverture d\'assurance',
    compliance_status: 'Statut de conformité',
    last_contact: 'Dernier contact',
    next_review: 'Prochaine révision',
    account_status: 'Statut du compte',
    relationship_manager: 'Gestionnaire de relation',
    onboarding_date: 'Date d\'intégration',
    contract_expiry: 'Expiration du contrat',
    renewal_date: 'Date de renouvellement',
    payment_terms: 'Conditions de paiement',
    credit_limit: 'Limite de crédit',
    outstanding_balance: 'Solde impayé',
    last_payment: 'Dernier paiement',
    payment_method: 'Méthode de paiement',
    billing_address: 'Adresse de facturation',
    tax_information: 'Informations fiscales',
    document_uploaded: 'Document téléchargé',
    status_updated: 'Statut mis à jour',
    meeting_scheduled: 'Réunion programmée',
    contract_renewed: 'Contrat renouvelé',
    issue_resolved: 'Problème résolu',
    feedback_received: 'Commentaire reçu',
    by: 'par',
    ago: 'il y a',
    minutes: 'minutes',
    hours: 'heures',
    weeks: 'semaines',
    months: 'mois',
    years: 'années',
    contract: 'Contrat',
    insurance_policy: 'Police d\'assurance',
    tax_certificate: 'Certificat fiscal',
    compliance_document: 'Document de conformité',
    financial_statement: 'État financier',
    size: 'Taille',
    download_document: 'Télécharger le document',
    view_document: 'Voir le document',
    document_details: 'Détails du document',
    no_documents_available: 'Aucun document disponible pour ce client.',
    upload_new_document: 'Télécharger un nouveau document',
    document_type: 'Type de document',
    file_size: 'Taille du fichier',
    upload_date: 'Date de téléchargement',
    uploaded_by: 'Téléchargé par',
    document_status: 'Statut du document',
    approved: 'Approuvé',
    pending_review: 'En attente de révision',
    rejected: 'Rejeté',
    expired: 'Expiré',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}