import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation & General
    dashboard: 'Dashboard',
    shipments: 'Shipments',
    documents: 'Documents',
    messages: 'Messages',
    invoices: 'Invoices',
    transit_files: 'Transit Files',
    clients: 'Clients',
    settings: 'Settings',
    profile: 'Profile',
    notifications: 'Notifications',
    loading: 'Loading...',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    create: 'Create',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    filters: 'Filters',
    clear: 'Clear',
    clearAll: 'Clear All',
    required: 'Required',
    optional: 'Optional',
    yes: 'Yes',
    no: 'No',
    confirm: 'Confirm',
    close: 'Close',
    submit: 'Submit',
    apply: 'Apply',
    reset: 'Reset',
    refresh: 'Refresh',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    sending: 'Sending...',
    saving: 'Saving...',
    creating: 'Creating...',
    updating: 'Updating...',
    deleting: 'Deleting...',
    processing: 'Processing...',
    completed: 'Completed',
    pending: 'Pending',
    active: 'Active',
    inactive: 'Inactive',
    enabled: 'Enabled',
    disabled: 'Disabled',
    available: 'Available',
    unavailable: 'Unavailable',
    online: 'Online',
    offline: 'Offline',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    
    // Authentication
    login: 'Sign In',
    logout: 'Sign Out',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    newPassword: 'New Password',
    currentPassword: 'Current Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    changePassword: 'Change Password',
    rememberMe: 'Remember me',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    invalidCredentials: 'Invalid email or password',
    portal: 'Logistics Management Portal',
    demoAccounts: 'Demo Accounts',
    english: 'English',
    french: 'Français',
    allRightsReserved: '© 2024 ShipTrack. All rights reserved.',
    
    // Password Reset
    resetPasswordInstructions: 'Enter your email address and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send Reset Link',
    resetEmailSent: 'Reset Email Sent',
    resetEmailSentDetails: 'We\'ve sent a password reset link to your email address.',
    resetEmailError: 'Failed to send reset email. Please try again.',
    backToLogin: 'Back to Login',
    createNewPassword: 'Create New Password',
    createNewPasswordInstructions: 'Your new password must be different from previous used passwords.',
    newPasswordPlaceholder: 'Enter your new password',
    confirmPasswordPlaceholder: 'Confirm your new password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordRequirementsNotMet: 'Password does not meet security requirements',
    resetPasswordError: 'Failed to reset password. Please try again.',
    passwordResetSuccess: 'Password Reset Successful',
    passwordResetSuccessDetails: 'Your password has been successfully reset. You can now sign in with your new password.',
    proceedToLogin: 'Proceed to Login',
    invalidResetToken: 'Invalid or expired reset token. Please request a new password reset.',
    resetting: 'Resetting...',
    minLength: 'At least 8 characters',
    upperCase: 'One uppercase letter',
    lowerCase: 'One lowercase letter',
    number: 'One number',
    specialChar: 'One special character',
    
    // User Roles
    client: 'Client',
    agent: 'Agent',
    operations: 'Operations',
    customs: 'Customs',
    finance: 'Finance',
    supervisor: 'Supervisor',
    admin: 'Administrator',
    
    // Shipment Status
    draft: 'Draft',
    warehouse: 'Warehouse',
    in_transit: 'In Transit',
    inTransit: 'In Transit',
    delivered: 'Delivered',
    issue: 'Issue',
    
    // Transport Types
    air: 'Air',
    sea: 'Sea',
    maritime: 'Maritime',
    aerial: 'Aerial',
    type_air: 'Air',
    type_sea: 'Sea',
    
    // Product Types
    standard: 'Standard',
    dangerous: 'Dangerous',
    fragile: 'Fragile',
    
    // Form Fields
    reference: 'Reference',
    file_reference: 'File Reference',
    bl_number: 'BL Number',
    enter_bl_number: 'Enter BL number',
    origin: 'Origin',
    destination: 'Destination',
    from: 'From',
    to: 'To',
    route: 'Route',
    weight: 'Weight',
    volume: 'Volume',
    capacity: 'Capacity',
    capacity_example: 'e.g., 20 feet, 15 tons',
    description: 'Description',
    content_description: 'Content Description',
    describe_content: 'Describe the content of this shipment...',
    transport_type: 'Transport Type',
    shipment_type: 'Shipment Type',
    product_type: 'Product Type',
    creation_date: 'Creation Date',
    creationDate: 'Creation Date',
    creation_date_from: 'Creation Date From',
    creation_date_to: 'Creation Date To',
    creationDateFrom: 'From Date',
    creationDateTo: 'To Date',
    estimated_delivery: 'Estimated Delivery',
    tracking_number: 'Tracking Number',
    city_country: 'City, Country',
    city_country_placeholder: 'e.g., Paris, France',
    cityCountryPlaceholder: 'e.g., Paris, France',
    
    // Client Management
    client_name: 'Client Name',
    client_email: 'Client Email',
    client_phone: 'Client Phone',
    client_company: 'Client Company',
    client_address: 'Client Address',
    client_city: 'Client City',
    client_country: 'Client Country',
    search_client: 'Search client...',
    select_client: 'Select a client',
    selected_clients: 'Selected Clients',
    add_clients: 'Add Clients',
    clients_selection: 'Clients Selection',
    createClient: 'Create Client',
    newClient: 'New Client',
    editClient: 'Edit Client',
    clientDetails: 'Client Details',
    manageClients: 'Manage Clients',
    noClientsFound: 'No clients found',
    allClients: 'All Clients',
    unknown_client: 'Unknown Client',
    
    // Agent Management
    agent_in_charge: 'Agent in Charge',
    assignedTo: 'Assigned To',
    assigned_to: 'Assigned To',
    search_agent: 'Search agent...',
    contact_agent: 'Contact Agent',
    contact_the_agent_in_charge: 'Contact the Agent in Charge',
    noAgentsFound: 'No agents found',
    allAgents: 'All Agents',
    
    // Documents
    invoice: 'Invoice',
    packing_list: 'Packing List',
    other_documents: 'Other Documents',
    uploaded_files: 'Uploaded Files',
    client_visible: 'Client Visible',
    file_visibility_settings: 'File Visibility Settings',
    
    // Containers
    containers: 'Containers',
    add_container: 'Add Container',
    add_first_container: 'Add First Container',
    no_containers_added: 'No containers added yet',
    container_number: 'Container Number',
    container_type: 'Container Type',
    container_size: 'Container Size',
    dry_container: 'Dry Container',
    refrigerated_container: 'Refrigerated Container',
    open_top_container: 'Open Top Container',
    flat_rack_container: 'Flat Rack Container',
    tank_container: 'Tank Container',
    other_container: 'Other Container',
    invalid_container_number_format: 'Invalid container number format',
    container_number_already_exists: 'Container number already exists',
    invalid_volume: 'Invalid volume',
    invalid_weight: 'Invalid weight',
    air_transport_selected: 'Air Transport Selected',
    containers_not_applicable_air: 'Containers are not applicable for air transport',
    
    // System Information
    system_information: 'System Information',
    general_information: 'General Information',
    route_and_capacity: 'Route and Capacity',
    
    // Transit Files
    new_transit_file: 'New Transit File',
    create_transit_file: 'Create a new transit file',
    create_transit_file_step_by_step: 'Create a new transit file step by step',
    clients_and_route: 'Clients & Route',
    cargo_details: 'Cargo Details',
    documents_and_events: 'Documents & Events',
    transit_file_created: 'Transit File Created',
    transit_file_created_desc: 'Your transit file has been successfully created.',
    view_file: 'View File',
    back_to_dashboard: 'Back to Dashboard',
    create_file: 'Create File',
    newFile: 'New File',
    manage_transit_files: 'Manage your transit files',
    
    // Dashboard
    manageFilesAndClients: 'Manage your files and clients',
    
    // Search and Filters
    searchPlaceholder: 'Search by reference, BL number, origin, destination...',
    allStatuses: 'All Statuses',
    allTypes: 'All Types',
    activeFilters: 'Active filters',
    filtered: 'filtered',
    sortBy: 'Sort by',
    itemsPerPage: 'Items per page',
    of: 'of',
    
    // Results
    filesFound: 'files found',
    files_found: 'files found',
    noFilesFound: 'No files found',
    no_files_found: 'No files found',
    noFilesFoundMessage: 'Try adjusting your search criteria or filters.',
    no_files_match_filters: 'No files match your current filters.',
    noFilesAvailable: 'No files available yet.',
    no_files_available: 'No files available yet.',
    clearFilters: 'Clear Filters',
    clear_all_filters: 'Clear All Filters',
    showLess: 'Show Less',
    show_less: 'Show Less',
    showAll: 'Show All ({count})',
    show_all: 'Show All ({count})',
    
    // Events Management
    events: 'Events',
    events_management: 'Events Management',
    events_management_desc: 'Manage the different stages of your transit file according to the type of operation.',
    date: 'Date',
    details: 'Details',
    optional_details: 'Optional details...',
    mark_completed: 'Mark as Completed',
    
    // Export Events
    export_pregate: 'Export Pre-gate (Document Reception)',
    warehouse_reception: 'Package Reception in Warehouse',
    declaration: 'Declaration',
    export_customs_clearance: 'Export Customs Clearance',
    warehouse_loading: 'Loading for Warehouse Exit',
    effective_transport: 'Effective Transport',
    vessel_loading: 'Vessel Loading (or Aircraft Loading)',
    departure: 'Departure',
    estimated_arrival: 'Estimated Arrival',
    billing: 'Billing',
    
    // Import Events
    import_prealert: 'Import Pre-alert (Document Reception)',
    arrival: 'Arrival',
    import_customs_clearance: 'Import Customs Clearance',
    maritime_company_slip: 'Maritime Company Slip (BAD)',
    import_pregate: 'Import Pre-gate (DO)',
    pickup: 'Pickup',
    delivery: 'Delivery',
    warehouse_arrival: 'Warehouse Arrival',
    
    // Notifications
    unread_count: '{count} unread',
    no_notifications: 'No notifications',
    mark_all_as_read: 'Mark all as read',
    view_all_notifications: 'View all notifications',
    
    // Messages
    write_your_message_here: 'Write your message here...',
    send_message: 'Send Message',
    message_sent_successfully: 'Message sent successfully',
    
    // Claims
    file_claim: 'File Claim',
    claim_type: 'Claim Type',
    select_claim_type: 'Select claim type',
    request_agent_change: 'Request Agent Change',
    delivery_issue: 'Delivery Issue',
    damaged_goods: 'Damaged Goods',
    missing_items: 'Missing Items',
    delay_complaint: 'Delay Complaint',
    billing_issue: 'Billing Issue',
    other: 'Other',
    shipment_reference: 'Shipment Reference',
    claim_agent_notification: 'Your claim will be sent directly to the agent in charge of your shipment.',
    write_your_claim_here: 'Write your claim here...',
    submit_claim: 'Submit Claim',
    claim_sent_successfully: 'Claim sent successfully',
    message: 'Message',
    
    // Password Change
    change_password: 'Change Password',
    password_change_instruction: 'For your security, please enter your current password to confirm your identity before setting a new password.',
    security_requirements: 'Security Requirements',
    password_req_length: 'At least 8 characters long',
    password_req_uppercase: 'Contains at least one uppercase letter',
    password_req_lowercase: 'Contains at least one lowercase letter',
    password_req_number: 'Contains at least one number',
    password_req_special: 'Contains at least one special character',
    error_current_password_required: 'Current password is required',
    error_password_requirements: 'Password does not meet security requirements',
    error_passwords_dont_match: 'Passwords do not match',
    save_changes: 'Save Changes',
    password_changed_successfully: 'Password changed successfully',
    
    // File Upload
    upload_file: 'Upload File',
    drag_files: 'Drag and drop files or click to browse',
    max_file_size: 'Maximum {size}MB per file',
    uploading_file: 'Uploading...',
    file_size_exceeded: 'File size exceeds the {size}MB limit',
    invalid_file_type: 'Unsupported file type, only images, videos, PDFs, Excel and Word files are accepted',
    remove_file: 'Remove',
    selected_files: 'Selected files',
    upload_success: 'Upload successful',
    upload_error: 'Upload error',
    upload_in_progress: 'Upload in progress',
  },
  fr: {
    // Navigation & General
    dashboard: 'Tableau de bord',
    shipments: 'Expéditions',
    documents: 'Documents',
    messages: 'Messages',
    invoices: 'Factures',
    transit_files: 'Dossiers de transit',
    clients: 'Clients',
    settings: 'Paramètres',
    profile: 'Profil',
    notifications: 'Notifications',
    loading: 'Chargement...',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    view: 'Voir',
    create: 'Créer',
    update: 'Mettre à jour',
    search: 'Rechercher',
    filter: 'Filtrer',
    filters: 'Filtres',
    clear: 'Effacer',
    clearAll: 'Tout effacer',
    required: 'Obligatoire',
    optional: 'Optionnel',
    yes: 'Oui',
    no: 'Non',
    confirm: 'Confirmer',
    close: 'Fermer',
    submit: 'Soumettre',
    apply: 'Appliquer',
    reset: 'Réinitialiser',
    refresh: 'Actualiser',
    export: 'Exporter',
    import: 'Importer',
    download: 'Télécharger',
    upload: 'Téléverser',
    sending: 'Envoi en cours...',
    saving: 'Enregistrement...',
    creating: 'Création...',
    updating: 'Mise à jour...',
    deleting: 'Suppression...',
    processing: 'Traitement...',
    completed: 'Terminé',
    pending: 'En attente',
    active: 'Actif',
    inactive: 'Inactif',
    enabled: 'Activé',
    disabled: 'Désactivé',
    available: 'Disponible',
    unavailable: 'Indisponible',
    online: 'En ligne',
    offline: 'Hors ligne',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    info: 'Information',
    
    // Authentication
    login: 'Se connecter',
    logout: 'Se déconnecter',
    signOut: 'Se déconnecter',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    newPassword: 'Nouveau mot de passe',
    currentPassword: 'Mot de passe actuel',
    forgotPassword: 'Mot de passe oublié ?',
    resetPassword: 'Réinitialiser le mot de passe',
    changePassword: 'Changer le mot de passe',
    rememberMe: 'Se souvenir de moi',
    emailPlaceholder: 'Entrez votre email',
    passwordPlaceholder: 'Entrez votre mot de passe',
    invalidCredentials: 'Email ou mot de passe invalide',
    portal: 'Portail de gestion logistique',
    demoAccounts: 'Comptes de démonstration',
    english: 'English',
    french: 'Français',
    allRightsReserved: '© 2024 ShipTrack. Tous droits réservés.',
    
    // Password Reset
    resetPasswordInstructions: 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
    sendResetLink: 'Envoyer le lien de réinitialisation',
    resetEmailSent: 'Email de réinitialisation envoyé',
    resetEmailSentDetails: 'Nous avons envoyé un lien de réinitialisation à votre adresse email.',
    resetEmailError: 'Échec de l\'envoi de l\'email de réinitialisation. Veuillez réessayer.',
    backToLogin: 'Retour à la connexion',
    createNewPassword: 'Créer un nouveau mot de passe',
    createNewPasswordInstructions: 'Votre nouveau mot de passe doit être différent des mots de passe précédemment utilisés.',
    newPasswordPlaceholder: 'Entrez votre nouveau mot de passe',
    confirmPasswordPlaceholder: 'Confirmez votre nouveau mot de passe',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordRequirementsNotMet: 'Le mot de passe ne respecte pas les exigences de sécurité',
    resetPasswordError: 'Échec de la réinitialisation du mot de passe. Veuillez réessayer.',
    passwordResetSuccess: 'Réinitialisation du mot de passe réussie',
    passwordResetSuccessDetails: 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    proceedToLogin: 'Procéder à la connexion',
    invalidResetToken: 'Token de réinitialisation invalide ou expiré. Veuillez demander une nouvelle réinitialisation.',
    resetting: 'Réinitialisation...',
    minLength: 'Au moins 8 caractères',
    upperCase: 'Une lettre majuscule',
    lowerCase: 'Une lettre minuscule',
    number: 'Un chiffre',
    specialChar: 'Un caractère spécial',
    
    // User Roles
    client: 'Client',
    agent: 'Agent',
    operations: 'Opérations',
    customs: 'Douanes',
    finance: 'Finance',
    supervisor: 'Superviseur',
    admin: 'Administrateur',
    
    // Shipment Status
    draft: 'Brouillon',
    warehouse: 'Entrepôt',
    in_transit: 'En transit',
    inTransit: 'En transit',
    delivered: 'Livré',
    issue: 'Problème',
    
    // Transport Types
    air: 'Aérien',
    sea: 'Maritime',
    maritime: 'Maritime',
    aerial: 'Aérien',
    type_air: 'Aérien',
    type_sea: 'Maritime',
    
    // Product Types
    standard: 'Standard',
    dangerous: 'Dangereux',
    fragile: 'Fragile',
    
    // Form Fields
    reference: 'Référence',
    file_reference: 'Référence du dossier',
    bl_number: 'Numéro BL',
    enter_bl_number: 'Entrez le numéro BL',
    origin: 'Origine',
    destination: 'Destination',
    from: 'De',
    to: 'Vers',
    route: 'Itinéraire',
    weight: 'Poids',
    volume: 'Volume',
    capacity: 'Capacité',
    capacity_example: 'ex: 20 pieds, 15 tonnes',
    description: 'Description',
    content_description: 'Description du contenu',
    describe_content: 'Décrivez le contenu de cette expédition...',
    transport_type: 'Type de transport',
    shipment_type: 'Type d\'expédition',
    product_type: 'Type de produit',
    creation_date: 'Date de création',
    creationDate: 'Date de création',
    creation_date_from: 'Date de création depuis',
    creation_date_to: 'Date de création jusqu\'à',
    creationDateFrom: 'Date de début',
    creationDateTo: 'Date de fin',
    estimated_delivery: 'Livraison estimée',
    tracking_number: 'Numéro de suivi',
    city_country: 'Ville, Pays',
    city_country_placeholder: 'ex: Paris, France',
    cityCountryPlaceholder: 'ex: Paris, France',
    
    // Client Management
    client_name: 'Nom du client',
    client_email: 'Email du client',
    client_phone: 'Téléphone du client',
    client_company: 'Entreprise du client',
    client_address: 'Adresse du client',
    client_city: 'Ville du client',
    client_country: 'Pays du client',
    search_client: 'Rechercher un client...',
    select_client: 'Sélectionner un client',
    selected_clients: 'Clients sélectionnés',
    add_clients: 'Ajouter des clients',
    clients_selection: 'Sélection des clients',
    createClient: 'Créer un client',
    newClient: 'Nouveau client',
    editClient: 'Modifier le client',
    clientDetails: 'Détails du client',
    manageClients: 'Gérer les clients',
    noClientsFound: 'Aucun client trouvé',
    allClients: 'Tous les clients',
    unknown_client: 'Client inconnu',
    
    // Agent Management
    agent_in_charge: 'Agent responsable',
    assignedTo: 'Assigné à',
    assigned_to: 'Assigné à',
    search_agent: 'Rechercher un agent...',
    contact_agent: 'Contacter l\'agent',
    contact_the_agent_in_charge: 'Contacter l\'agent responsable',
    noAgentsFound: 'Aucun agent trouvé',
    allAgents: 'Tous les agents',
    
    // Documents
    invoice: 'Facture',
    packing_list: 'Liste de colisage',
    other_documents: 'Autres documents',
    uploaded_files: 'Fichiers téléversés',
    client_visible: 'Visible par le client',
    file_visibility_settings: 'Paramètres de visibilité des fichiers',
    
    // Containers
    containers: 'Conteneurs',
    add_container: 'Ajouter un conteneur',
    add_first_container: 'Ajouter le premier conteneur',
    no_containers_added: 'Aucun conteneur ajouté',
    container_number: 'Numéro de conteneur',
    container_type: 'Type de conteneur',
    container_size: 'Taille du conteneur',
    dry_container: 'Conteneur sec',
    refrigerated_container: 'Conteneur réfrigéré',
    open_top_container: 'Conteneur open top',
    flat_rack_container: 'Conteneur flat rack',
    tank_container: 'Conteneur citerne',
    other_container: 'Autre conteneur',
    invalid_container_number_format: 'Format de numéro de conteneur invalide',
    container_number_already_exists: 'Le numéro de conteneur existe déjà',
    invalid_volume: 'Volume invalide',
    invalid_weight: 'Poids invalide',
    air_transport_selected: 'Transport aérien sélectionné',
    containers_not_applicable_air: 'Les conteneurs ne s\'appliquent pas au transport aérien',
    
    // System Information
    system_information: 'Informations système',
    general_information: 'Informations générales',
    route_and_capacity: 'Itinéraire et capacité',
    
    // Transit Files
    new_transit_file: 'Nouveau dossier de transit',
    create_transit_file: 'Créer un nouveau dossier de transit',
    create_transit_file_step_by_step: 'Créer un nouveau dossier de transit étape par étape',
    clients_and_route: 'Clients et itinéraire',
    cargo_details: 'Détails de la cargaison',
    documents_and_events: 'Documents et événements',
    transit_file_created: 'Dossier de transit créé',
    transit_file_created_desc: 'Votre dossier de transit a été créé avec succès.',
    view_file: 'Voir le dossier',
    back_to_dashboard: 'Retour au tableau de bord',
    create_file: 'Créer le dossier',
    newFile: 'Nouveau dossier',
    manage_transit_files: 'Gérer vos dossiers de transit',
    
    // Dashboard
    manageFilesAndClients: 'Gérez vos dossiers et clients',
    
    // Search and Filters
    searchPlaceholder: 'Rechercher par référence, numéro BL, origine, destination...',
    allStatuses: 'Tous les statuts',
    allTypes: 'Tous les types',
    activeFilters: 'Filtres actifs',
    filtered: 'filtré(s)',
    sortBy: 'Trier par',
    itemsPerPage: 'Éléments par page',
    of: 'sur',
    
    // Results
    filesFound: 'dossiers trouvés',
    files_found: 'dossiers trouvés',
    noFilesFound: 'Aucun dossier trouvé',
    no_files_found: 'Aucun dossier trouvé',
    noFilesFoundMessage: 'Essayez d\'ajuster vos critères de recherche ou filtres.',
    no_files_match_filters: 'Aucun dossier ne correspond à vos filtres actuels.',
    noFilesAvailable: 'Aucun dossier disponible pour le moment.',
    no_files_available: 'Aucun dossier disponible pour le moment.',
    clearFilters: 'Effacer les filtres',
    clear_all_filters: 'Effacer tous les filtres',
    showLess: 'Afficher moins',
    show_less: 'Afficher moins',
    showAll: 'Tout afficher ({count})',
    show_all: 'Tout afficher ({count})',
    
    // Events Management
    events: 'Événements',
    events_management: 'Gestion des événements',
    events_management_desc: 'Gérez les différentes étapes de votre dossier de transit selon le type d\'opération.',
    date: 'Date',
    details: 'Détails',
    optional_details: 'Détails optionnels...',
    mark_completed: 'Marquer comme terminé',
    
    // Export Events
    export_pregate: 'Prégate export (Réception documents)',
    warehouse_reception: 'Réception colis dans l\'entrepôt',
    declaration: 'Déclaration',
    export_customs_clearance: 'Bon de douane export',
    warehouse_loading: 'Chargement pour sortie entrepôt',
    effective_transport: 'Transport effectif',
    vessel_loading: 'Chargement dans le navire (ou chargement dans avion)',
    departure: 'Départ',
    estimated_arrival: 'Estimation arrivée',
    billing: 'Facturation',
    
    // Import Events
    import_prealert: 'Préalerte import (Réception documents)',
    arrival: 'Arrivée',
    import_customs_clearance: 'Bon de douane import',
    maritime_company_slip: 'Bordereau Compagnie Maritime (BAD)',
    import_pregate: 'Prégate d\'import (DO)',
    pickup: 'Enlèvement',
    delivery: 'Livraison',
    warehouse_arrival: 'Arrivée entrepôt',
    
    // Notifications
    unread_count: '{count} non lu(s)',
    no_notifications: 'Aucune notification',
    mark_all_as_read: 'Tout marquer comme lu',
    view_all_notifications: 'Voir toutes les notifications',
    
    // Messages
    write_your_message_here: 'Écrivez votre message ici...',
    send_message: 'Envoyer le message',
    message_sent_successfully: 'Message envoyé avec succès',
    
    // Claims
    file_claim: 'Déposer une réclamation',
    claim_type: 'Type de réclamation',
    select_claim_type: 'Sélectionner le type de réclamation',
    request_agent_change: 'Demande de changement d\'agent',
    delivery_issue: 'Problème de livraison',
    damaged_goods: 'Marchandises endommagées',
    missing_items: 'Articles manquants',
    delay_complaint: 'Plainte pour retard',
    billing_issue: 'Problème de facturation',
    other: 'Autre',
    shipment_reference: 'Référence de l\'expédition',
    claim_agent_notification: 'Votre réclamation sera envoyée directement à l\'agent responsable de votre expédition.',
    write_your_claim_here: 'Écrivez votre réclamation ici...',
    submit_claim: 'Soumettre la réclamation',
    claim_sent_successfully: 'Réclamation envoyée avec succès',
    message: 'Message',
    
    // Password Change
    change_password: 'Changer le mot de passe',
    password_change_instruction: 'Pour votre sécurité, veuillez entrer votre mot de passe actuel pour confirmer votre identité avant de définir un nouveau mot de passe.',
    security_requirements: 'Exigences de sécurité',
    password_req_length: 'Au moins 8 caractères',
    password_req_uppercase: 'Contient au moins une lettre majuscule',
    password_req_lowercase: 'Contient au moins une lettre minuscule',
    password_req_number: 'Contient au moins un chiffre',
    password_req_special: 'Contient au moins un caractère spécial',
    error_current_password_required: 'Le mot de passe actuel est requis',
    error_password_requirements: 'Le mot de passe ne respecte pas les exigences de sécurité',
    error_passwords_dont_match: 'Les mots de passe ne correspondent pas',
    save_changes: 'Enregistrer les modifications',
    password_changed_successfully: 'Mot de passe modifié avec succès',
    
    // File Upload
    upload_file: 'Téléverser un fichier',
    drag_files: 'Glissez-déposez des fichiers ou cliquez pour parcourir',
    max_file_size: 'Maximum {size}MB par fichier',
    uploading_file: 'Téléversement...',
    file_size_exceeded: 'La taille du fichier dépasse la limite de {size}MB',
    invalid_file_type: 'Type de fichier non pris en charge, seuls les images, vidéos, PDFs, fichiers Excel et Word sont acceptés',
    remove_file: 'Supprimer',
    selected_files: 'Fichiers sélectionnés',
    upload_success: 'Téléversement réussi',
    upload_error: 'Erreur de téléversement',
    upload_in_progress: 'Téléversement en cours',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || translations['en'][key] || key;
    
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};